export interface LocalizedText { en: string; ko?: string; ja?: string; fr?: string; es?: string; zh?: string; de?: string }

export interface DemoCard {
  id: string;
  front: string;        // Basic: target word / Cloze: sentence with _____
  back: LocalizedText;   // Basic: meaning / Cloze: answer word (localized)
  pronunciation: string; // romanization (shown in accent color)
  noteType?: 'Basic' | 'Cloze';
  extra?: string;       // Cloze: full sentence
}

export type DemoLang = 'ko' | 'ja' | 'en' | 'fr' | 'es' | 'zh' | 'de';

export interface DemoDeck {
  id: string;
  lang: DemoLang;
  name: string;
  nameLocal: string;    // native language name (한국어 기초, 日本語 基礎, etc.)
  description: string;
  emoji: string;
  accentColor: string;
  cards: DemoCard[];
}

export const DEMO_DECKS: DemoDeck[] = [
  {
    id: 'korean-basics',
    lang: 'ko',
    name: 'Korean Basics',
    nameLocal: '한국어 기초',
    description: 'Essential everyday Korean vocabulary — perfect for beginners.',
    emoji: '🇰🇷',
    accentColor: '#3730a3',
    cards: [
      { id: 'kb-01', front: '사랑', back: { en: 'love', ko: '사랑', ja: '愛' }, pronunciation: 'sarang' },
      { id: 'kb-02', front: '행복', back: { en: 'happiness', ko: '행복', ja: '幸せ' }, pronunciation: 'haengbok' },
      { id: 'kb-03', front: '친구', back: { en: 'friend', ko: '친구', ja: '友達' }, pronunciation: 'chingu' },
      { id: 'kb-04', front: '가족', back: { en: 'family', ko: '가족', ja: '家族' }, pronunciation: 'gajok' },
      { id: 'kb-05', front: '집', back: { en: 'home', ko: '집', ja: '家' }, pronunciation: 'jip' },
      { id: 'kb-06', front: '음식', back: { en: 'food', ko: '음식', ja: '食べ物' }, pronunciation: 'eumsik' },
      { id: 'kb-07', front: '음악', back: { en: 'music', ko: '음악', ja: '音楽' }, pronunciation: 'eumak' },
      { id: 'kb-08', front: '하늘', back: { en: 'sky', ko: '하늘', ja: '空' }, pronunciation: 'haneul' },
      { id: 'kb-09', front: '꿈', back: { en: 'dream', ko: '꿈', ja: '夢' }, pronunciation: 'kkum' },
      { id: 'kb-10', front: '시간', back: { en: 'time', ko: '시간', ja: '時間' }, pronunciation: 'sigan' },
      { id: 'kb-11', front: '학교', back: { en: 'school', ko: '학교', ja: '学校' }, pronunciation: 'hakgyo' },
      { id: 'kb-12', front: '물', back: { en: 'water', ko: '물', ja: '水' }, pronunciation: 'mul' },
      { id: 'kb-13', front: '빛', back: { en: 'light', ko: '빛', ja: '光' }, pronunciation: 'bit' },
      { id: 'kb-14', front: '책', back: { en: 'book', ko: '책', ja: '本' }, pronunciation: 'chaek' },
      { id: 'kb-15', front: '고양이', back: { en: 'cat', ko: '고양이', ja: '猫' }, pronunciation: 'goyangi' },
      // Cloze cards
      { id: 'kb-c01', noteType: 'Cloze', front: '나는 가족을 _____합니다.', back: { en: 'love', ko: '사랑', ja: '愛' }, pronunciation: 'love', extra: '나는 가족을 사랑합니다.' },
      { id: 'kb-c02', noteType: 'Cloze', front: '함께 있으면 _____해요.', back: { en: 'happiness', ko: '행복', ja: '幸せ' }, pronunciation: 'happiness', extra: '함께 있으면 행복해요.' },
      { id: 'kb-c03', noteType: 'Cloze', front: '_____에서 열심히 공부해요.', back: { en: 'school', ko: '학교', ja: '学校' }, pronunciation: 'school', extra: '학교에서 열심히 공부해요.' },
      { id: 'kb-c04', noteType: 'Cloze', front: '좋은 _____을 들으면 기분이 좋아요.', back: { en: 'music', ko: '음악', ja: '音楽' }, pronunciation: 'music', extra: '좋은 음악을 들으면 기분이 좋아요.' },
      { id: 'kb-c05', noteType: 'Cloze', front: '파란 _____을 바라보며 꿈을 꿔요.', back: { en: 'sky', ko: '하늘', ja: '空' }, pronunciation: 'sky', extra: '파란 하늘을 바라보며 꿈을 꿔요.' },
    ],
  },
  {
    id: 'kdrama',
    lang: 'ko',
    name: 'K-Drama Essentials',
    nameLocal: '드라마 필수 단어',
    description: 'Words from Squid Game, Crash Landing on You, and more hit dramas.',
    emoji: '🎬',
    accentColor: '#831843',
    cards: [
      { id: 'kd-01', front: '운명', back: { en: 'fate', ko: '운명', ja: '運命' }, pronunciation: 'unmyeong' },
      { id: 'kd-02', front: '기억', back: { en: 'memory', ko: '기억', ja: '記憶' }, pronunciation: 'gieok' },
      { id: 'kd-03', front: '비밀', back: { en: 'secret', ko: '비밀', ja: '秘密' }, pronunciation: 'bimil' },
      { id: 'kd-04', front: '용기', back: { en: 'courage', ko: '용기', ja: '勇気' }, pronunciation: 'yonggi' },
      { id: 'kd-05', front: '희망', back: { en: 'hope', ko: '희망', ja: '希望' }, pronunciation: 'huimang' },
      { id: 'kd-06', front: '눈물', back: { en: 'tears', ko: '눈물', ja: '涙' }, pronunciation: 'nunmul' },
      { id: 'kd-07', front: '선택', back: { en: 'choice', ko: '선택', ja: '選択' }, pronunciation: 'seonteok' },
      { id: 'kd-08', front: '게임', back: { en: 'game', ko: '게임', ja: 'ゲーム' }, pronunciation: 'geim' },
      { id: 'kd-09', front: '진실', back: { en: 'truth', ko: '진실', ja: '真実' }, pronunciation: 'jinsil' },
      { id: 'kd-10', front: '배신', back: { en: 'betrayal', ko: '배신', ja: '裏切り' }, pronunciation: 'baesin' },
      { id: 'kd-11', front: '복수', back: { en: 'revenge', ko: '복수', ja: '復讐' }, pronunciation: 'boksu' },
      { id: 'kd-12', front: '기회', back: { en: 'opportunity', ko: '기회', ja: '機会' }, pronunciation: 'gihoe' },
      { id: 'kd-13', front: '그리움', back: { en: 'longing', ko: '그리움', ja: '恋しさ' }, pronunciation: 'geuriwum' },
      { id: 'kd-14', front: '마음', back: { en: 'heart', ko: '마음', ja: '心' }, pronunciation: 'maeum' },
      { id: 'kd-15', front: '상금', back: { en: 'prize money', ko: '상금', ja: '賞金' }, pronunciation: 'sanggeum' },
      // Cloze cards
      { id: 'kd-c01', noteType: 'Cloze', front: '우리가 만난 건 _____이었어요.', back: { en: 'destiny', ko: '운명', ja: '運命' }, pronunciation: 'destiny', extra: '우리가 만난 건 운명이었어요.' },
      { id: 'kd-c02', noteType: 'Cloze', front: '아직 _____을 잃지 마세요.', back: { en: 'hope', ko: '희망', ja: '希望' }, pronunciation: 'hope', extra: '아직 희망을 잃지 마세요.' },
      { id: 'kd-c03', noteType: 'Cloze', front: '그녀의 눈에 _____이 흘렀어요.', back: { en: 'tears', ko: '눈물', ja: '涙' }, pronunciation: 'tears', extra: '그녀의 눈에 눈물이 흘렀어요.' },
      { id: 'kd-c04', noteType: 'Cloze', front: '당신의 _____을 믿어요.', back: { en: 'heart', ko: '마음', ja: '心' }, pronunciation: 'heart', extra: '당신의 마음을 믿어요.' },
      { id: 'kd-c05', noteType: 'Cloze', front: '모든 것에는 나만의 _____가 있어요.', back: { en: 'secret', ko: '비밀', ja: '秘密' }, pronunciation: 'secret', extra: '모든 것에는 나만의 비밀이 있어요.' },
    ],
  },
  {
    id: 'kpop',
    lang: 'ko',
    name: 'K-Pop Vocabulary',
    nameLocal: 'K-팝 단어',
    description: 'Words from BTS, BLACKPINK, TWICE and more iconic songs.',
    emoji: '🎤',
    accentColor: '#065f46',
    cards: [
      { id: 'kp-01', front: '우주', back: { en: 'universe', ko: '우주', ja: '宇宙' }, pronunciation: 'uju' },
      { id: 'kp-02', front: '별', back: { en: 'star', ko: '별', ja: '星' }, pronunciation: 'byeol' },
      { id: 'kp-03', front: '영원', back: { en: 'eternity', ko: '영원', ja: '永遠' }, pronunciation: 'yeongwon' },
      { id: 'kp-04', front: '노래', back: { en: 'song', ko: '노래', ja: '歌' }, pronunciation: 'norae' },
      { id: 'kp-05', front: '춤', back: { en: 'dance', ko: '춤', ja: 'ダンス' }, pronunciation: 'chum' },
      { id: 'kp-06', front: '자유', back: { en: 'freedom', ko: '자유', ja: '自由' }, pronunciation: 'jayu' },
      { id: 'kp-07', front: '설레임', back: { en: 'flutter', ko: '설레임', ja: 'ときめき' }, pronunciation: 'seolleim' },
      { id: 'kp-08', front: '함께', back: { en: 'together', ko: '함께', ja: '一緒に' }, pronunciation: 'hamkke' },
      { id: 'kp-09', front: '소리', back: { en: 'sound', ko: '소리', ja: '音' }, pronunciation: 'sori' },
      { id: 'kp-10', front: '태양', back: { en: 'sun', ko: '태양', ja: '太陽' }, pronunciation: 'taeyang' },
      { id: 'kp-11', front: '파도', back: { en: 'wave', ko: '파도', ja: '波' }, pronunciation: 'pado' },
      { id: 'kp-12', front: '이야기', back: { en: 'story', ko: '이야기', ja: '物語' }, pronunciation: 'iyagi' },
      { id: 'kp-13', front: '행운', back: { en: 'good luck', ko: '행운', ja: '幸運' }, pronunciation: 'haengun' },
      { id: 'kp-14', front: '반짝', back: { en: 'sparkle', ko: '반짝', ja: 'きらめき' }, pronunciation: 'banjjak' },
      { id: 'kp-15', front: '세상', back: { en: 'world', ko: '세상', ja: '世界' }, pronunciation: 'sesang' },
      // Cloze cards
      { id: 'kp-c01', noteType: 'Cloze', front: '저 _____처럼 빛나고 싶어.', back: { en: 'star', ko: '별', ja: '星' }, pronunciation: 'star', extra: '저 별처럼 빛나고 싶어.' },
      { id: 'kp-c02', noteType: 'Cloze', front: '우리 _____히 같이 있자.', back: { en: 'forever', ko: '영원', ja: '永遠' }, pronunciation: 'forever', extra: '우리 영원히 같이 있자.' },
      { id: 'kp-c03', noteType: 'Cloze', front: '온 _____이 우리 편이야.', back: { en: 'world', ko: '세상', ja: '世界' }, pronunciation: 'world', extra: '온 세상이 우리 편이야.' },
      { id: 'kp-c04', noteType: 'Cloze', front: '네 _____가 나를 설레게 해.', back: { en: 'song', ko: '노래', ja: '歌' }, pronunciation: 'song', extra: '네 노래가 나를 설레게 해.' },
      { id: 'kp-c05', noteType: 'Cloze', front: '네가 있는 곳이 내 _____야.', back: { en: 'universe', ko: '우주', ja: '宇宙' }, pronunciation: 'universe', extra: '네가 있는 곳이 내 우주야.' },
    ],
  },
  {
    id: 'kpop-fandom',
    lang: 'ko',
    name: 'K-Pop Fandom Terms',
    nameLocal: 'K-팝 팬덤 용어',
    description: 'Essential fandom terms every K-pop fan should know — 컴백, 팬싸, 응원봉 and more.',
    emoji: '💜',
    accentColor: '#7c3aed',
    cards: [
      { id: 'kf-01', front: '컴백', back: { en: 'comeback', ko: '컴백', ja: 'カムバック' }, pronunciation: 'keombaek' },
      { id: 'kf-02', front: '팬싸', back: { en: 'fan signing event', ko: '팬싸인회', ja: 'サイン会' }, pronunciation: 'paenssa' },
      { id: 'kf-03', front: '응원봉', back: { en: 'lightstick', ko: '응원봉', ja: 'ペンライト' }, pronunciation: 'eungwonbong' },
      { id: 'kf-04', front: '덕질', back: { en: 'fangirling/fanboying', ko: '덕질', ja: 'オタ活' }, pronunciation: 'deokjil' },
      { id: 'kf-05', front: '최애', back: { en: 'ultimate bias', ko: '최애', ja: '推し' }, pronunciation: 'choeae' },
      { id: 'kf-06', front: '무대', back: { en: 'stage', ko: '무대', ja: 'ステージ' }, pronunciation: 'mudae' },
      { id: 'kf-07', front: '안무', back: { en: 'choreography', ko: '안무', ja: '振り付け' }, pronunciation: 'anmu' },
      { id: 'kf-08', front: '음원', back: { en: 'digital release', ko: '음원', ja: '音源' }, pronunciation: 'eumwon' },
      { id: 'kf-09', front: '총공', back: { en: 'mass streaming', ko: '총공', ja: '総攻撃' }, pronunciation: 'chonggong' },
      { id: 'kf-10', front: '직캠', back: { en: 'fancam', ko: '직캠', ja: 'ファンカム' }, pronunciation: 'jikcam' },
      { id: 'kf-11', front: '떡밥', back: { en: 'teaser/hint', ko: '떡밥', ja: 'ティーザー' }, pronunciation: 'tteokbap' },
      { id: 'kf-12', front: '입덕', back: { en: 'becoming a fan', ko: '입덕', ja: '推し始め' }, pronunciation: 'ipdeok' },
      { id: 'kf-13', front: '탈덕', back: { en: 'leaving fandom', ko: '탈덕', ja: '推し卒' }, pronunciation: 'taldeok' },
      { id: 'kf-14', front: '멤버', back: { en: 'member', ko: '멤버', ja: 'メンバー' }, pronunciation: 'membeo' },
      { id: 'kf-15', front: '공연', back: { en: 'concert/performance', ko: '공연', ja: 'コンサート' }, pronunciation: 'gongyeon' },
      // Cloze cards
      { id: 'kf-c01', noteType: 'Cloze', front: '오늘 _____에서 최애를 만났어요!', back: { en: 'fan signing event', ko: '팬싸인회', ja: 'サイン会' }, pronunciation: 'fan signing event', extra: '오늘 팬싸에서 최애를 만났어요!' },
      { id: 'kf-c02', noteType: 'Cloze', front: '새 앨범 _____이 드디어 발표됐어요.', back: { en: 'comeback', ko: '컴백', ja: 'カムバック' }, pronunciation: 'comeback', extra: '새 앨범 컴백이 드디어 발표됐어요.' },
      { id: 'kf-c03', noteType: 'Cloze', front: '_____을 흔들며 함께 노래했어요.', back: { en: 'lightstick', ko: '응원봉', ja: 'ペンライト' }, pronunciation: 'lightstick', extra: '응원봉을 흔들며 함께 노래했어요.' },
      { id: 'kf-c04', noteType: 'Cloze', front: '이 _____는 정말 대단해요!', back: { en: 'choreography', ko: '안무', ja: '振り付け' }, pronunciation: 'choreography', extra: '이 안무는 정말 대단해요!' },
      { id: 'kf-c05', noteType: 'Cloze', front: '내 _____는 이 그룹의 리더예요.', back: { en: 'favorite member', ko: '최애', ja: '推し' }, pronunciation: 'favorite member', extra: '내 최애는 이 그룹의 리더예요.' },
    ],
  },
  {
    id: 'kpop-emotions',
    lang: 'ko',
    name: 'K-Pop Emotion Words',
    nameLocal: 'K-팝 감성 단어',
    description: 'Deep emotional vocabulary found in K-pop ballads and love songs.',
    emoji: '🌙',
    accentColor: '#be185d',
    cards: [
      { id: 'ke-01', front: '그리움', back: { en: 'longing/yearning', ko: '그리움', ja: '恋しさ' }, pronunciation: 'geuriwum' },
      { id: 'ke-02', front: '설렘', back: { en: 'excitement/flutter', ko: '설렘', ja: 'ときめき' }, pronunciation: 'seollem' },
      { id: 'ke-03', front: '이별', back: { en: 'farewell/breakup', ko: '이별', ja: '別れ' }, pronunciation: 'ibyeol' },
      { id: 'ke-04', front: '추억', back: { en: 'memories', ko: '추억', ja: '思い出' }, pronunciation: 'chueok' },
      { id: 'ke-05', front: '눈물', back: { en: 'tears', ko: '눈물', ja: '涙' }, pronunciation: 'nunmul' },
      { id: 'ke-06', front: '약속', back: { en: 'promise', ko: '약속', ja: '約束' }, pronunciation: 'yaksok' },
      { id: 'ke-07', front: '고백', back: { en: 'confession', ko: '고백', ja: '告白' }, pronunciation: 'gobaek' },
      { id: 'ke-08', front: '위로', back: { en: 'comfort', ko: '위로', ja: '慰め' }, pronunciation: 'wiro' },
      { id: 'ke-09', front: '기다림', back: { en: 'waiting', ko: '기다림', ja: '待つこと' }, pronunciation: 'gidarim' },
      { id: 'ke-10', front: '외로움', back: { en: 'loneliness', ko: '외로움', ja: '寂しさ' }, pronunciation: 'oeroum' },
      { id: 'ke-11', front: '떨림', back: { en: 'trembling', ko: '떨림', ja: '震え' }, pronunciation: 'tteollim' },
      { id: 'ke-12', front: '바램', back: { en: 'wish/hope', ko: '바램', ja: '願い' }, pronunciation: 'baraem' },
      { id: 'ke-13', front: '미련', back: { en: 'lingering attachment', ko: '미련', ja: '未練' }, pronunciation: 'miryeon' },
      { id: 'ke-14', front: '아픔', back: { en: 'pain/heartache', ko: '아픔', ja: '痛み' }, pronunciation: 'apeum' },
      { id: 'ke-15', front: '봄날', back: { en: 'spring day', ko: '봄날', ja: '春の日' }, pronunciation: 'bomnal' },
      // Cloze cards
      { id: 'ke-c01', noteType: 'Cloze', front: '너를 향한 _____이 멈추지 않아.', back: { en: 'longing', ko: '그리움', ja: '恋しさ' }, pronunciation: 'longing', extra: '너를 향한 그리움이 멈추지 않아.' },
      { id: 'ke-c02', noteType: 'Cloze', front: '이 _____을 영원히 간직할게.', back: { en: 'memory', ko: '추억', ja: '思い出' }, pronunciation: 'memory', extra: '이 추억을 영원히 간직할게.' },
      { id: 'ke-c03', noteType: 'Cloze', front: '너에게 _____을 하고 싶어.', back: { en: 'confession', ko: '고백', ja: '告白' }, pronunciation: 'confession', extra: '너에게 고백을 하고 싶어.' },
      { id: 'ke-c04', noteType: 'Cloze', front: '긴 _____의 끝에 네가 왔어.', back: { en: 'waiting', ko: '기다림', ja: '待つこと' }, pronunciation: 'waiting', extra: '긴 기다림의 끝에 네가 왔어.' },
      { id: 'ke-c05', noteType: 'Cloze', front: '_____이 지나면 다시 만날 거야.', back: { en: 'spring day', ko: '봄날', ja: '春の日' }, pronunciation: 'spring day', extra: '봄날이 지나면 다시 만날 거야.' },
    ],
  },
  {
    id: 'japanese-basics',
    lang: 'ja',
    name: 'Japanese Basics',
    nameLocal: '日本語 基礎',
    description: 'Essential everyday Japanese vocabulary — perfect for beginners.',
    emoji: '🇯🇵',
    accentColor: '#dc2626',
    cards: [
      { id: 'jb-01', front: '愛', back: { en: 'love', ko: '사랑', ja: '愛' }, pronunciation: 'ai' },
      { id: 'jb-02', front: '友達', back: { en: 'friend', ko: '친구', ja: '友達' }, pronunciation: 'tomodachi' },
      { id: 'jb-03', front: '家族', back: { en: 'family', ko: '가족', ja: '家族' }, pronunciation: 'kazoku' },
      { id: 'jb-04', front: '学校', back: { en: 'school', ko: '학교', ja: '学校' }, pronunciation: 'gakkou' },
      { id: 'jb-05', front: '食べ物', back: { en: 'food', ko: '음식', ja: '食べ物' }, pronunciation: 'tabemono' },
      { id: 'jb-06', front: '音楽', back: { en: 'music', ko: '음악', ja: '音楽' }, pronunciation: 'ongaku' },
      { id: 'jb-07', front: '空', back: { en: 'sky', ko: '하늘', ja: '空' }, pronunciation: 'sora' },
      { id: 'jb-08', front: '夢', back: { en: 'dream', ko: '꿈', ja: '夢' }, pronunciation: 'yume' },
      { id: 'jb-09', front: '時間', back: { en: 'time', ko: '시간', ja: '時間' }, pronunciation: 'jikan' },
      { id: 'jb-10', front: '水', back: { en: 'water', ko: '물', ja: '水' }, pronunciation: 'mizu' },
      { id: 'jb-11', front: '光', back: { en: 'light', ko: '빛', ja: '光' }, pronunciation: 'hikari' },
      { id: 'jb-12', front: '本', back: { en: 'book', ko: '책', ja: '本' }, pronunciation: 'hon' },
      { id: 'jb-13', front: '猫', back: { en: 'cat', ko: '고양이', ja: '猫' }, pronunciation: 'neko' },
      { id: 'jb-14', front: '花', back: { en: 'flower', ko: '꽃', ja: '花' }, pronunciation: 'hana' },
      { id: 'jb-15', front: '心', back: { en: 'heart', ko: '마음', ja: '心' }, pronunciation: 'kokoro' },
      // Cloze cards
      { id: 'jb-c01', noteType: 'Cloze', front: '毎日_____を飲みます。', back: { en: 'water', ko: '물', ja: '水' }, pronunciation: 'water', extra: '毎日水を飲みます。' },
      { id: 'jb-c02', noteType: 'Cloze', front: '_____が青くて綺麗です。', back: { en: 'sky', ko: '하늘', ja: '空' }, pronunciation: 'sky', extra: '空が青くて綺麗です。' },
      { id: 'jb-c03', noteType: 'Cloze', front: '好きな_____は寿司です。', back: { en: 'food', ko: '음식', ja: '食べ物' }, pronunciation: 'food', extra: '好きな食べ物は寿司です。' },
      { id: 'jb-c04', noteType: 'Cloze', front: '毎朝_____を聴きます。', back: { en: 'music', ko: '음악', ja: '音楽' }, pronunciation: 'music', extra: '毎朝音楽を聴きます。' },
      { id: 'jb-c05', noteType: 'Cloze', front: '彼女の_____はとても優しい。', back: { en: 'heart', ko: '마음', ja: '心' }, pronunciation: 'heart', extra: '彼女の心はとても優しい。' },
    ],
  },
  {
    id: 'anime',
    lang: 'ja',
    name: 'Anime Essentials',
    nameLocal: 'アニメ必須単語',
    description: 'Words from Naruto, One Piece, Demon Slayer and more hit anime.',
    emoji: '⛩️',
    accentColor: '#7c3aed',
    cards: [
      { id: 'an-01', front: '仲間', back: { en: 'companion', ko: '동료', ja: '仲間' }, pronunciation: 'nakama' },
      { id: 'an-02', front: '約束', back: { en: 'promise', ko: '약속', ja: '約束' }, pronunciation: 'yakusoku' },
      { id: 'an-03', front: '勇気', back: { en: 'courage', ko: '용기', ja: '勇気' }, pronunciation: 'yuuki' },
      { id: 'an-04', front: '戦い', back: { en: 'battle', ko: '전투', ja: '戦い' }, pronunciation: 'tatakai' },
      { id: 'an-05', front: '希望', back: { en: 'hope', ko: '희망', ja: '希望' }, pronunciation: 'kibou' },
      { id: 'an-06', front: '力', back: { en: 'power', ko: '힘', ja: '力' }, pronunciation: 'chikara' },
      { id: 'an-07', front: '運命', back: { en: 'destiny', ko: '운명', ja: '運命' }, pronunciation: 'unmei' },
      { id: 'an-08', front: '守る', back: { en: 'protect', ko: '지키다', ja: '守る' }, pronunciation: 'mamoru' },
      { id: 'an-09', front: '魔法', back: { en: 'magic', ko: '마법', ja: '魔法' }, pronunciation: 'mahou' },
      { id: 'an-10', front: '冒険', back: { en: 'adventure', ko: '모험', ja: '冒険' }, pronunciation: 'bouken' },
      { id: 'an-11', front: '正義', back: { en: 'justice', ko: '정의', ja: '正義' }, pronunciation: 'seigi' },
      { id: 'an-12', front: '絆', back: { en: 'bond', ko: '유대', ja: '絆' }, pronunciation: 'kizuna' },
      { id: 'an-13', front: '覚悟', back: { en: 'resolve', ko: '각오', ja: '覚悟' }, pronunciation: 'kakugo' },
      { id: 'an-14', front: '修行', back: { en: 'training', ko: '수련', ja: '修行' }, pronunciation: 'shugyou' },
      { id: 'an-15', front: '英雄', back: { en: 'hero', ko: '영웅', ja: '英雄' }, pronunciation: 'eiyuu' },
      // Cloze cards
      { id: 'an-c01', noteType: 'Cloze', front: '友達との_____は必ず守る。', back: { en: 'promise', ko: '약속', ja: '約束' }, pronunciation: 'promise', extra: '友達との約束は必ず守る。' },
      { id: 'an-c02', noteType: 'Cloze', front: '君を_____ために戦い続ける。', back: { en: 'to protect', ko: '지키다', ja: '守る' }, pronunciation: 'to protect', extra: '君を守るために戦い続ける。' },
      { id: 'an-c03', noteType: 'Cloze', front: 'これが僕たちの_____だ。', back: { en: 'fate', ko: '운명', ja: '運命' }, pronunciation: 'fate', extra: 'これが僕たちの運命だ。' },
      { id: 'an-c04', noteType: 'Cloze', front: '_____の力で世界を救う。', back: { en: 'magic', ko: '마법', ja: '魔法' }, pronunciation: 'magic', extra: '魔法の力で世界を救う。' },
      { id: 'an-c05', noteType: 'Cloze', front: '諦めない_____がある限り。', back: { en: 'courage', ko: '용기', ja: '勇気' }, pronunciation: 'courage', extra: '諦めない勇気がある限り。' },
    ],
  },
  {
    id: 'jpop',
    lang: 'ja',
    name: 'J-Pop Vocabulary',
    nameLocal: 'J-ポップ単語',
    description: 'Words from YOASOBI, Ado, Kenshi Yonezu and more iconic songs.',
    emoji: '🎵',
    accentColor: '#0891b2',
    cards: [
      { id: 'jp-01', front: '桜', back: { en: 'cherry blossom', ko: '벚꽃', ja: '桜' }, pronunciation: 'sakura' },
      { id: 'jp-02', front: '永遠', back: { en: 'eternity', ko: '영원', ja: '永遠' }, pronunciation: 'eien' },
      { id: 'jp-03', front: '涙', back: { en: 'tears', ko: '눈물', ja: '涙' }, pronunciation: 'namida' },
      { id: 'jp-04', front: '世界', back: { en: 'world', ko: '세계', ja: '世界' }, pronunciation: 'sekai' },
      { id: 'jp-05', front: '星', back: { en: 'star', ko: '별', ja: '星' }, pronunciation: 'hoshi' },
      { id: 'jp-06', front: '歌', back: { en: 'song', ko: '노래', ja: '歌' }, pronunciation: 'uta' },
      { id: 'jp-07', front: '風', back: { en: 'wind', ko: '바람', ja: '風' }, pronunciation: 'kaze' },
      { id: 'jp-08', front: '恋', back: { en: 'romance', ko: '사랑', ja: '恋' }, pronunciation: 'koi' },
      { id: 'jp-09', front: '明日', back: { en: 'tomorrow', ko: '내일', ja: '明日' }, pronunciation: 'ashita' },
      { id: 'jp-10', front: '輝き', back: { en: 'radiance', ko: '빛남', ja: '輝き' }, pronunciation: 'kagayaki' },
      { id: 'jp-11', front: '願い', back: { en: 'wish', ko: '소원', ja: '願い' }, pronunciation: 'negai' },
      { id: 'jp-12', front: '声', back: { en: 'voice', ko: '목소리', ja: '声' }, pronunciation: 'koe' },
      { id: 'jp-13', front: '旅', back: { en: 'journey', ko: '여행', ja: '旅' }, pronunciation: 'tabi' },
      { id: 'jp-14', front: '未来', back: { en: 'future', ko: '미래', ja: '未来' }, pronunciation: 'mirai' },
      { id: 'jp-15', front: '海', back: { en: 'sea', ko: '바다', ja: '海' }, pronunciation: 'umi' },
      // Cloze cards
      { id: 'jp-c01', noteType: 'Cloze', front: 'あなたの_____が聴こえる。', back: { en: 'voice', ko: '목소리', ja: '声' }, pronunciation: 'voice', extra: 'あなたの声が聴こえる。' },
      { id: 'jp-c02', noteType: 'Cloze', front: '春には_____が咲く。', back: { en: 'cherry blossom', ko: '벚꽃', ja: '桜' }, pronunciation: 'cherry blossom', extra: '春には桜が咲く。' },
      { id: 'jp-c03', noteType: 'Cloze', front: '瞳に_____が光る。', back: { en: 'tears', ko: '눈물', ja: '涙' }, pronunciation: 'tears', extra: '瞳に涙が光る。' },
      { id: 'jp-c04', noteType: 'Cloze', front: '君と_____に旅したい。', back: { en: 'eternity', ko: '영원', ja: '永遠' }, pronunciation: 'eternity', extra: '君と永遠に旅したい。' },
      { id: 'jp-c05', noteType: 'Cloze', front: '君への_____は届くだろう。', back: { en: 'wish', ko: '소원', ja: '願い' }, pronunciation: 'wish', extra: '君への願いは届くだろう。' },
    ],
  },
  // ─── English Decks ────────────────────────────────────────────────
  {
    id: 'english-basics',
    lang: 'en',
    name: 'English Basics',
    nameLocal: 'English Basics',
    description: 'Essential English vocabulary for everyday communication.',
    emoji: '🇺🇸',
    accentColor: '#2563eb',
    cards: [
      { id: 'eb-01', front: 'appreciate', back: { en: 'to value highly', ko: '감사하다', ja: '感謝する' }, pronunciation: 'uh-PREE-shee-ayt' },
      { id: 'eb-02', front: 'opportunity', back: { en: 'a favorable chance', ko: '기회', ja: '機会' }, pronunciation: 'op-er-TOO-nuh-tee' },
      { id: 'eb-03', front: 'experience', back: { en: 'practical knowledge', ko: '경험', ja: '経験' }, pronunciation: 'ik-SPEER-ee-uhns' },
      { id: 'eb-04', front: 'challenge', back: { en: 'a difficult task', ko: '도전', ja: '挑戦' }, pronunciation: 'CHAL-inj' },
      { id: 'eb-05', front: 'confidence', back: { en: 'belief in oneself', ko: '자신감', ja: '自信' }, pronunciation: 'KON-fih-duhns' },
      { id: 'eb-06', front: 'determine', back: { en: 'to decide firmly', ko: '결정하다', ja: '決定する' }, pronunciation: 'dih-TUR-min' },
      { id: 'eb-07', front: 'environment', back: { en: 'surroundings', ko: '환경', ja: '環境' }, pronunciation: 'en-VY-ruhn-muhnt' },
      { id: 'eb-08', front: 'knowledge', back: { en: 'information learned', ko: '지식', ja: '知識' }, pronunciation: 'NOL-ij' },
      { id: 'eb-09', front: 'responsibility', back: { en: 'a duty to deal with', ko: '책임', ja: '責任' }, pronunciation: 'rih-spon-suh-BIL-uh-tee' },
      { id: 'eb-10', front: 'communicate', back: { en: 'to share information', ko: '소통하다', ja: '伝える' }, pronunciation: 'kuh-MYOO-nih-kayt' },
      { id: 'eb-11', front: 'accomplish', back: { en: 'to achieve', ko: '달성하다', ja: '達成する' }, pronunciation: 'uh-KOM-plish' },
      { id: 'eb-12', front: 'encourage', back: { en: 'to give support', ko: '격려하다', ja: '励ます' }, pronunciation: 'en-KUR-ij' },
      { id: 'eb-13', front: 'perspective', back: { en: 'a point of view', ko: '관점', ja: '視点' }, pronunciation: 'per-SPEK-tiv' },
      { id: 'eb-14', front: 'independent', back: { en: 'self-reliant', ko: '독립적인', ja: '独立した' }, pronunciation: 'in-duh-PEN-duhnt' },
      { id: 'eb-15', front: 'volunteer', back: { en: 'to offer help freely', ko: '자원봉사하다', ja: 'ボランティアする' }, pronunciation: 'vol-uhn-TEER' },
      // Cloze cards
      { id: 'eb-c01', noteType: 'Cloze', front: 'I really _____ your help.', back: { en: 'appreciate', ko: '감사하다', ja: '感謝する' }, pronunciation: 'uh-PREE-shee-ayt', extra: 'I really appreciate your help.' },
      { id: 'eb-c02', noteType: 'Cloze', front: 'This is a great _____ to learn.', back: { en: 'opportunity', ko: '기회', ja: '機会' }, pronunciation: 'op-er-TOO-nuh-tee', extra: 'This is a great opportunity to learn.' },
      { id: 'eb-c03', noteType: 'Cloze', front: 'She has a lot of _____ in herself.', back: { en: 'confidence', ko: '자신감', ja: '自信' }, pronunciation: 'KON-fih-duhns', extra: 'She has a lot of confidence in herself.' },
      { id: 'eb-c04', noteType: 'Cloze', front: 'We need to _____ more effectively.', back: { en: 'communicate', ko: '소통하다', ja: '伝える' }, pronunciation: 'kuh-MYOO-nih-kayt', extra: 'We need to communicate more effectively.' },
      { id: 'eb-c05', noteType: 'Cloze', front: 'It is your _____ to finish this.', back: { en: 'responsibility', ko: '책임', ja: '責任' }, pronunciation: 'rih-spon-suh-BIL-uh-tee', extra: 'It is your responsibility to finish this.' },
    ],
  },
  {
    id: 'travel-english',
    lang: 'en',
    name: 'Travel English',
    nameLocal: 'Travel English',
    description: 'Essential English vocabulary for traveling abroad.',
    emoji: '✈️',
    accentColor: '#059669',
    cards: [
      { id: 'et-01', front: 'reservation', back: { en: 'a booking', ko: '예약', ja: '予約' }, pronunciation: 'rez-er-VAY-shuhn' },
      { id: 'et-02', front: 'departure', back: { en: 'the act of leaving', ko: '출발', ja: '出発' }, pronunciation: 'dih-PAR-chur' },
      { id: 'et-03', front: 'accommodation', back: { en: 'a place to stay', ko: '숙소', ja: '宿泊施設' }, pronunciation: 'uh-kom-uh-DAY-shuhn' },
      { id: 'et-04', front: 'destination', back: { en: 'a place to go', ko: '목적지', ja: '目的地' }, pronunciation: 'des-tuh-NAY-shuhn' },
      { id: 'et-05', front: 'itinerary', back: { en: 'a travel plan', ko: '여행일정', ja: '旅程' }, pronunciation: 'eye-TIN-uh-rer-ee' },
      { id: 'et-06', front: 'passport', back: { en: 'travel document', ko: '여권', ja: 'パスポート' }, pronunciation: 'PAS-port' },
      { id: 'et-07', front: 'luggage', back: { en: 'bags for travel', ko: '짐', ja: '荷物' }, pronunciation: 'LUG-ij' },
      { id: 'et-08', front: 'currency', back: { en: 'money system', ko: '통화', ja: '通貨' }, pronunciation: 'KUR-uhn-see' },
      { id: 'et-09', front: 'customs', back: { en: 'border inspection', ko: '세관', ja: '税関' }, pronunciation: 'KUS-tuhmz' },
      { id: 'et-10', front: 'souvenir', back: { en: 'a memento', ko: '기념품', ja: 'お土産' }, pronunciation: 'soo-vuh-NEER' },
      { id: 'et-11', front: 'navigate', back: { en: 'to find the way', ko: '길을 찾다', ja: '道を探す' }, pronunciation: 'NAV-ih-gayt' },
      { id: 'et-12', front: 'layover', back: { en: 'a stop between flights', ko: '경유', ja: '乗り継ぎ' }, pronunciation: 'LAY-oh-ver' },
      { id: 'et-13', front: 'excursion', back: { en: 'a short trip', ko: '소풍', ja: '遠足' }, pronunciation: 'ik-SKUR-zhuhn' },
      { id: 'et-14', front: 'embassy', back: { en: 'diplomatic office', ko: '대사관', ja: '大使館' }, pronunciation: 'EM-buh-see' },
      { id: 'et-15', front: 'boarding', back: { en: 'getting on a vehicle', ko: '탑승', ja: '搭乗' }, pronunciation: 'BOR-ding' },
      // Cloze cards
      { id: 'et-c01', noteType: 'Cloze', front: 'I have a _____ at the hotel.', back: { en: 'reservation', ko: '예약', ja: '予約' }, pronunciation: 'rez-er-VAY-shuhn', extra: 'I have a reservation at the hotel.' },
      { id: 'et-c02', noteType: 'Cloze', front: 'Our _____ time is 3 PM.', back: { en: 'departure', ko: '출발', ja: '出発' }, pronunciation: 'dih-PAR-chur', extra: 'Our departure time is 3 PM.' },
      { id: 'et-c03', noteType: 'Cloze', front: 'What is the final _____?', back: { en: 'destination', ko: '목적지', ja: '目的地' }, pronunciation: 'des-tuh-NAY-shuhn', extra: 'What is the final destination?' },
      { id: 'et-c04', noteType: 'Cloze', front: "Don't forget your _____.", back: { en: 'passport', ko: '여권', ja: 'パスポート' }, pronunciation: 'PAS-port', extra: "Don't forget your passport." },
      { id: 'et-c05', noteType: 'Cloze', front: 'I bought a _____ for my friend.', back: { en: 'souvenir', ko: '기념품', ja: 'お土産' }, pronunciation: 'soo-vuh-NEER', extra: 'I bought a souvenir for my friend.' },
    ],
  },
  {
    id: 'business-english',
    lang: 'en',
    name: 'Business English',
    nameLocal: 'Business English',
    description: 'Professional vocabulary for the workplace and meetings.',
    emoji: '💼',
    accentColor: '#d97706',
    cards: [
      { id: 'bu-01', front: 'negotiate', back: { en: 'to discuss terms', ko: '협상하다', ja: '交渉する' }, pronunciation: 'nih-GOH-shee-ayt' },
      { id: 'bu-02', front: 'deadline', back: { en: 'a time limit', ko: '마감', ja: '締め切り' }, pronunciation: 'DED-line' },
      { id: 'bu-03', front: 'strategy', back: { en: 'a plan of action', ko: '전략', ja: '戦略' }, pronunciation: 'STRAT-uh-jee' },
      { id: 'bu-04', front: 'collaborate', back: { en: 'to work together', ko: '협력하다', ja: '協力する' }, pronunciation: 'kuh-LAB-uh-rayt' },
      { id: 'bu-05', front: 'proposal', back: { en: 'a suggested plan', ko: '제안', ja: '提案' }, pronunciation: 'pruh-POH-zuhl' },
      { id: 'bu-06', front: 'revenue', back: { en: 'income earned', ko: '수익', ja: '収益' }, pronunciation: 'REV-uh-noo' },
      { id: 'bu-07', front: 'investment', back: { en: 'putting money to use', ko: '투자', ja: '投資' }, pronunciation: 'in-VEST-muhnt' },
      { id: 'bu-08', front: 'productivity', back: { en: 'work efficiency', ko: '생산성', ja: '生産性' }, pronunciation: 'proh-duk-TIV-uh-tee' },
      { id: 'bu-09', front: 'stakeholder', back: { en: 'an interested party', ko: '이해관계자', ja: '利害関係者' }, pronunciation: 'STAYK-hohl-der' },
      { id: 'bu-10', front: 'implement', back: { en: 'to put into action', ko: '실행하다', ja: '実行する' }, pronunciation: 'IM-pluh-ment' },
      { id: 'bu-11', front: 'analyze', back: { en: 'to examine in detail', ko: '분석하다', ja: '分析する' }, pronunciation: 'AN-uh-lyze' },
      { id: 'bu-12', front: 'feedback', back: { en: 'response or comments', ko: '피드백', ja: 'フィードバック' }, pronunciation: 'FEED-bak' },
      { id: 'bu-13', front: 'milestone', back: { en: 'an important stage', ko: '이정표', ja: 'マイルストーン' }, pronunciation: 'MILE-stohn' },
      { id: 'bu-14', front: 'delegate', back: { en: 'to assign tasks', ko: '위임하다', ja: '委任する' }, pronunciation: 'DEL-uh-gayt' },
      { id: 'bu-15', front: 'innovative', back: { en: 'introducing new ideas', ko: '혁신적인', ja: '革新的な' }, pronunciation: 'IN-uh-vay-tiv' },
      // Cloze cards
      { id: 'bu-c01', noteType: 'Cloze', front: 'We need to _____ the contract terms.', back: { en: 'negotiate', ko: '협상하다', ja: '交渉する' }, pronunciation: 'nih-GOH-shee-ayt', extra: 'We need to negotiate the contract terms.' },
      { id: 'bu-c02', noteType: 'Cloze', front: 'The _____ is next Friday.', back: { en: 'deadline', ko: '마감', ja: '締め切り' }, pronunciation: 'DED-line', extra: 'The deadline is next Friday.' },
      { id: 'bu-c03', noteType: 'Cloze', front: "Let's _____ on this project.", back: { en: 'collaborate', ko: '협력하다', ja: '協力する' }, pronunciation: 'kuh-LAB-uh-rayt', extra: "Let's collaborate on this project." },
      { id: 'bu-c04', noteType: 'Cloze', front: 'We should _____ the data first.', back: { en: 'analyze', ko: '분석하다', ja: '分析する' }, pronunciation: 'AN-uh-lyze', extra: 'We should analyze the data first.' },
      { id: 'bu-c05', noteType: 'Cloze', front: 'This is an _____ approach.', back: { en: 'innovative', ko: '혁신적인', ja: '革新的な' }, pronunciation: 'IN-uh-vay-tiv', extra: 'This is an innovative approach.' },
    ],
  },
  // ─── Additional English Decks ──────────────────────────────────────
  {
    id: 'english-idioms',
    lang: 'en',
    name: 'English Idioms',
    nameLocal: 'English Idioms',
    description: 'Common English idioms and expressions used in daily conversation.',
    emoji: '🗣️',
    accentColor: '#6d28d9',
    cards: [
      { id: 'ei-01', front: 'break the ice', back: { en: 'to start a conversation', ko: '어색함을 깨다', ja: '場を和ませる' }, pronunciation: 'brayk thuh ais' },
      { id: 'ei-02', front: 'piece of cake', back: { en: 'something very easy', ko: '아주 쉬운 일', ja: 'とても簡単なこと' }, pronunciation: 'pees uhv kayk' },
      { id: 'ei-03', front: 'hit the nail on the head', back: { en: 'to be exactly right', ko: '정곡을 찌르다', ja: '的を射る' }, pronunciation: 'hit thuh nayl' },
      { id: 'ei-04', front: 'under the weather', back: { en: 'feeling sick', ko: '몸이 안 좋은', ja: '体調が悪い' }, pronunciation: 'UN-der thuh WEH-ther' },
      { id: 'ei-05', front: 'cost an arm and a leg', back: { en: 'very expensive', ko: '매우 비싼', ja: 'とても高い' }, pronunciation: 'kost an arm' },
      { id: 'ei-06', front: 'let the cat out of the bag', back: { en: 'to reveal a secret', ko: '비밀을 누설하다', ja: '秘密を漏らす' }, pronunciation: 'let thuh kat out' },
      { id: 'ei-07', front: 'bite the bullet', back: { en: 'to face something difficult', ko: '이를 악물고 하다', ja: '歯を食いしばる' }, pronunciation: 'bait thuh BUL-it' },
      { id: 'ei-08', front: 'once in a blue moon', back: { en: 'very rarely', ko: '아주 드물게', ja: 'めったにない' }, pronunciation: 'wuns in uh bloo moon' },
      { id: 'ei-09', front: 'a blessing in disguise', back: { en: 'good thing that seemed bad', ko: '전화위복', ja: '不幸中の幸い' }, pronunciation: 'uh BLES-ing in dis-GAIZ' },
      { id: 'ei-10', front: 'the best of both worlds', back: { en: 'enjoying two advantages', ko: '두 가지 장점 모두', ja: '一石二鳥' }, pronunciation: 'thuh best uhv bohth wurldz' },
      { id: 'ei-11', front: 'speak of the devil', back: { en: 'the person just appeared', ko: '호랑이도 제 말 하면', ja: '噂をすれば' }, pronunciation: 'speek uhv thuh DEV-ul' },
      { id: 'ei-12', front: 'on cloud nine', back: { en: 'extremely happy', ko: '매우 행복한', ja: 'とても幸せ' }, pronunciation: 'on kloud nain' },
      { id: 'ei-13', front: 'spill the beans', back: { en: 'to reveal information', ko: '비밀을 말하다', ja: '秘密を暴露する' }, pronunciation: 'spil thuh beenz' },
      { id: 'ei-14', front: 'pull someone\'s leg', back: { en: 'to joke with someone', ko: '놀리다', ja: 'からかう' }, pronunciation: 'pul SUM-wunz leg' },
      { id: 'ei-15', front: 'burn the midnight oil', back: { en: 'to work late at night', ko: '밤늦게까지 일하다', ja: '夜遅くまで働く' }, pronunciation: 'burn thuh MID-nait oil' },
      { id: 'ei-c01', noteType: 'Cloze', front: 'Let me _____ — my name is Alex.', back: { en: 'break the ice', ko: '어색함을 깨다', ja: '場を和ませる' }, pronunciation: 'break the ice', extra: 'Let me break the ice — my name is Alex.' },
      { id: 'ei-c02', noteType: 'Cloze', front: 'The exam was a _____.', back: { en: 'piece of cake', ko: '아주 쉬운 일', ja: 'とても簡単なこと' }, pronunciation: 'piece of cake', extra: 'The exam was a piece of cake.' },
      { id: 'ei-c03', noteType: 'Cloze', front: 'I\'m feeling _____ today.', back: { en: 'under the weather', ko: '몸이 안 좋은', ja: '体調が悪い' }, pronunciation: 'under the weather', extra: "I'm feeling under the weather today." },
      { id: 'ei-c04', noteType: 'Cloze', front: 'That car _____.', back: { en: 'cost an arm and a leg', ko: '매우 비쌌다', ja: 'とても高かった' }, pronunciation: 'cost an arm and a leg', extra: 'That car cost an arm and a leg.' },
      { id: 'ei-c05', noteType: 'Cloze', front: 'She\'s been _____ studying for finals.', back: { en: 'burning the midnight oil', ko: '밤늦게까지 공부하다', ja: '夜遅くまで勉強する' }, pronunciation: 'burning the midnight oil', extra: "She's been burning the midnight oil studying for finals." },
    ],
  },
  {
    id: 'english-academic',
    lang: 'en',
    name: 'Academic English',
    nameLocal: 'Academic English',
    description: 'Advanced vocabulary for research papers, essays, and university courses.',
    emoji: '🎓',
    accentColor: '#1e40af',
    cards: [
      { id: 'ea-01', front: 'hypothesis', back: { en: 'an educated guess', ko: '가설', ja: '仮説' }, pronunciation: 'hy-POTH-uh-sis' },
      { id: 'ea-02', front: 'methodology', back: { en: 'a system of methods', ko: '방법론', ja: '方法論' }, pronunciation: 'meth-uh-DOL-uh-jee' },
      { id: 'ea-03', front: 'phenomenon', back: { en: 'an observable event', ko: '현상', ja: '現象' }, pronunciation: 'fuh-NOM-uh-non' },
      { id: 'ea-04', front: 'paradigm', back: { en: 'a model or framework', ko: '패러다임', ja: 'パラダイム' }, pronunciation: 'PAIR-uh-dime' },
      { id: 'ea-05', front: 'empirical', back: { en: 'based on observation', ko: '경험적인', ja: '経験的な' }, pronunciation: 'em-PEER-ih-kul' },
      { id: 'ea-06', front: 'synthesis', back: { en: 'combining ideas', ko: '종합', ja: '総合' }, pronunciation: 'SIN-thuh-sis' },
      { id: 'ea-07', front: 'quantitative', back: { en: 'measured by numbers', ko: '양적인', ja: '定量的な' }, pronunciation: 'KWON-tuh-tay-tiv' },
      { id: 'ea-08', front: 'qualitative', back: { en: 'measured by quality', ko: '질적인', ja: '定性的な' }, pronunciation: 'KWOL-uh-tay-tiv' },
      { id: 'ea-09', front: 'correlation', back: { en: 'a mutual relationship', ko: '상관관계', ja: '相関関係' }, pronunciation: 'kor-uh-LAY-shun' },
      { id: 'ea-10', front: 'ambiguous', back: { en: 'unclear in meaning', ko: '모호한', ja: '曖昧な' }, pronunciation: 'am-BIG-yoo-us' },
      { id: 'ea-11', front: 'comprehensive', back: { en: 'thorough and complete', ko: '포괄적인', ja: '包括的な' }, pronunciation: 'kom-pruh-HEN-siv' },
      { id: 'ea-12', front: 'implication', back: { en: 'a possible effect', ko: '시사점', ja: '含意' }, pronunciation: 'im-plih-KAY-shun' },
      { id: 'ea-13', front: 'prevalent', back: { en: 'widespread', ko: '널리 퍼진', ja: '普及している' }, pronunciation: 'PREV-uh-lunt' },
      { id: 'ea-14', front: 'scrutinize', back: { en: 'to examine closely', ko: '면밀히 조사하다', ja: '精査する' }, pronunciation: 'SKROO-tuh-nize' },
      { id: 'ea-15', front: 'criterion', back: { en: 'a standard for judging', ko: '기준', ja: '基準' }, pronunciation: 'kry-TEER-ee-un' },
      { id: 'ea-c01', noteType: 'Cloze', front: 'Our _____ was proven correct.', back: { en: 'hypothesis', ko: '가설', ja: '仮説' }, pronunciation: 'hypothesis', extra: 'Our hypothesis was proven correct.' },
      { id: 'ea-c02', noteType: 'Cloze', front: 'The research _____ was clearly defined.', back: { en: 'methodology', ko: '방법론', ja: '方法論' }, pronunciation: 'methodology', extra: 'The research methodology was clearly defined.' },
      { id: 'ea-c03', noteType: 'Cloze', front: 'This _____ has been studied for decades.', back: { en: 'phenomenon', ko: '현상', ja: '現象' }, pronunciation: 'phenomenon', extra: 'This phenomenon has been studied for decades.' },
      { id: 'ea-c04', noteType: 'Cloze', front: 'The data shows a strong _____.', back: { en: 'correlation', ko: '상관관계', ja: '相関関係' }, pronunciation: 'correlation', extra: 'The data shows a strong correlation.' },
      { id: 'ea-c05', noteType: 'Cloze', front: 'We need to _____ the results carefully.', back: { en: 'scrutinize', ko: '면밀히 조사하다', ja: '精査する' }, pronunciation: 'scrutinize', extra: 'We need to scrutinize the results carefully.' },
    ],
  },
  // ─── Additional Japanese Decks ─────────────────────────────────────
  {
    id: 'japanese-travel',
    lang: 'ja',
    name: 'Japanese Travel',
    nameLocal: '日本語 旅行',
    description: 'Essential Japanese vocabulary for traveling in Japan.',
    emoji: '🗾',
    accentColor: '#b91c1c',
    cards: [
      { id: 'jt-01', front: '切符', back: { en: 'ticket', ko: '표', ja: '切符' }, pronunciation: 'kippu' },
      { id: 'jt-02', front: '駅', back: { en: 'station', ko: '역', ja: '駅' }, pronunciation: 'eki' },
      { id: 'jt-03', front: '空港', back: { en: 'airport', ko: '공항', ja: '空港' }, pronunciation: 'kuukou' },
      { id: 'jt-04', front: '地図', back: { en: 'map', ko: '지도', ja: '地図' }, pronunciation: 'chizu' },
      { id: 'jt-05', front: '予約', back: { en: 'reservation', ko: '예약', ja: '予約' }, pronunciation: 'yoyaku' },
      { id: 'jt-06', front: '旅館', back: { en: 'Japanese inn', ko: '료칸', ja: '旅館' }, pronunciation: 'ryokan' },
      { id: 'jt-07', front: '温泉', back: { en: 'hot spring', ko: '온천', ja: '温泉' }, pronunciation: 'onsen' },
      { id: 'jt-08', front: '新幹線', back: { en: 'bullet train', ko: '신칸센', ja: '新幹線' }, pronunciation: 'shinkansen' },
      { id: 'jt-09', front: '両替', back: { en: 'currency exchange', ko: '환전', ja: '両替' }, pronunciation: 'ryougae' },
      { id: 'jt-10', front: '出口', back: { en: 'exit', ko: '출구', ja: '出口' }, pronunciation: 'deguchi' },
      { id: 'jt-11', front: '入口', back: { en: 'entrance', ko: '입구', ja: '入口' }, pronunciation: 'iriguchi' },
      { id: 'jt-12', front: '案内', back: { en: 'information/guide', ko: '안내', ja: '案内' }, pronunciation: 'annai' },
      { id: 'jt-13', front: '荷物', back: { en: 'luggage', ko: '짐', ja: '荷物' }, pronunciation: 'nimotsu' },
      { id: 'jt-14', front: '観光', back: { en: 'sightseeing', ko: '관광', ja: '観光' }, pronunciation: 'kankou' },
      { id: 'jt-15', front: 'お土産', back: { en: 'souvenir', ko: '기념품', ja: 'お土産' }, pronunciation: 'omiyage' },
      { id: 'jt-c01', noteType: 'Cloze', front: '_____を買って電車に乗ります。', back: { en: 'ticket', ko: '표', ja: '切符' }, pronunciation: 'ticket', extra: '切符を買って電車に乗ります。' },
      { id: 'jt-c02', noteType: 'Cloze', front: '東京_____に到着しました。', back: { en: 'station', ko: '역', ja: '駅' }, pronunciation: 'station', extra: '東京駅に到着しました。' },
      { id: 'jt-c03', noteType: 'Cloze', front: 'ホテルの_____を取りました。', back: { en: 'reservation', ko: '예약', ja: '予約' }, pronunciation: 'reservation', extra: 'ホテルの予約を取りました。' },
      { id: 'jt-c04', noteType: 'Cloze', front: '日本の_____はとても気持ちいい。', back: { en: 'hot spring', ko: '온천', ja: '温泉' }, pronunciation: 'hot spring', extra: '日本の温泉はとても気持ちいい。' },
      { id: 'jt-c05', noteType: 'Cloze', front: '友達に_____を買いました。', back: { en: 'souvenir', ko: '기념품', ja: 'お土産' }, pronunciation: 'souvenir', extra: '友達にお土産を買いました。' },
    ],
  },
  {
    id: 'japanese-food',
    lang: 'ja',
    name: 'Japanese Food',
    nameLocal: '日本語 食べ物',
    description: 'Popular Japanese food vocabulary — sushi, ramen, tempura and more.',
    emoji: '🍣',
    accentColor: '#ea580c',
    cards: [
      { id: 'jf-01', front: '寿司', back: { en: 'sushi', ko: '스시', ja: '寿司' }, pronunciation: 'sushi' },
      { id: 'jf-02', front: '天ぷら', back: { en: 'tempura', ko: '튀김', ja: '天ぷら' }, pronunciation: 'tenpura' },
      { id: 'jf-03', front: 'ラーメン', back: { en: 'ramen noodles', ko: '라면', ja: 'ラーメン' }, pronunciation: 'raamen' },
      { id: 'jf-04', front: 'うどん', back: { en: 'udon noodles', ko: '우동', ja: 'うどん' }, pronunciation: 'udon' },
      { id: 'jf-05', front: '刺身', back: { en: 'sashimi', ko: '회', ja: '刺身' }, pronunciation: 'sashimi' },
      { id: 'jf-06', front: '焼肉', back: { en: 'grilled meat', ko: '야키니쿠', ja: '焼肉' }, pronunciation: 'yakiniku' },
      { id: 'jf-07', front: '味噌汁', back: { en: 'miso soup', ko: '미소시루', ja: '味噌汁' }, pronunciation: 'misoshiru' },
      { id: 'jf-08', front: 'おにぎり', back: { en: 'rice ball', ko: '주먹밥', ja: 'おにぎり' }, pronunciation: 'onigiri' },
      { id: 'jf-09', front: '弁当', back: { en: 'lunch box', ko: '도시락', ja: '弁当' }, pronunciation: 'bentou' },
      { id: 'jf-10', front: '抹茶', back: { en: 'matcha green tea', ko: '말차', ja: '抹茶' }, pronunciation: 'matcha' },
      { id: 'jf-11', front: '餃子', back: { en: 'dumplings', ko: '교자', ja: '餃子' }, pronunciation: 'gyouza' },
      { id: 'jf-12', front: 'たこ焼き', back: { en: 'takoyaki', ko: '타코야키', ja: 'たこ焼き' }, pronunciation: 'takoyaki' },
      { id: 'jf-13', front: '醤油', back: { en: 'soy sauce', ko: '간장', ja: '醤油' }, pronunciation: 'shouyu' },
      { id: 'jf-14', front: '和菓子', back: { en: 'Japanese sweets', ko: '화과자', ja: '和菓子' }, pronunciation: 'wagashi' },
      { id: 'jf-15', front: '居酒屋', back: { en: 'Japanese pub', ko: '이자카야', ja: '居酒屋' }, pronunciation: 'izakaya' },
      { id: 'jf-c01', noteType: 'Cloze', front: '日本で一番好きな食べ物は_____です。', back: { en: 'sushi', ko: '스시', ja: '寿司' }, pronunciation: 'sushi', extra: '日本で一番好きな食べ物は寿司です。' },
      { id: 'jf-c02', noteType: 'Cloze', front: '寒い日には_____が美味しい。', back: { en: 'ramen', ko: '라면', ja: 'ラーメン' }, pronunciation: 'ramen', extra: '寒い日にはラーメンが美味しい。' },
      { id: 'jf-c03', noteType: 'Cloze', front: '朝ごはんに_____を食べました。', back: { en: 'rice ball', ko: '주먹밥', ja: 'おにぎり' }, pronunciation: 'rice ball', extra: '朝ごはんにおにぎりを食べました。' },
      { id: 'jf-c04', noteType: 'Cloze', front: '_____をつけて食べてください。', back: { en: 'soy sauce', ko: '간장', ja: '醤油' }, pronunciation: 'soy sauce', extra: '醤油をつけて食べてください。' },
      { id: 'jf-c05', noteType: 'Cloze', front: '金曜日の夜は_____に行きます。', back: { en: 'Japanese pub', ko: '이자카야', ja: '居酒屋' }, pronunciation: 'Japanese pub', extra: '金曜日の夜は居酒屋に行きます。' },
    ],
  },
  // ─── French Decks ──────────────────────────────────────────────────
  {
    id: 'french-basics',
    lang: 'fr',
    name: 'French Basics',
    nameLocal: 'Français de base',
    description: 'Essential everyday French vocabulary — perfect for beginners.',
    emoji: '🇫🇷',
    accentColor: '#1d4ed8',
    cards: [
      { id: 'fb-01', front: 'bonjour', back: { en: 'hello', fr: 'bonjour', ko: '안녕하세요', ja: 'こんにちは' }, pronunciation: 'bohn-ZHOOR' },
      { id: 'fb-02', front: 'merci', back: { en: 'thank you', fr: 'merci', ko: '감사합니다', ja: 'ありがとう' }, pronunciation: 'mair-SEE' },
      { id: 'fb-03', front: 'amour', back: { en: 'love', fr: 'amour', ko: '사랑', ja: '愛' }, pronunciation: 'ah-MOOR' },
      { id: 'fb-04', front: 'maison', back: { en: 'house', fr: 'maison', ko: '집', ja: '家' }, pronunciation: 'meh-ZOHN' },
      { id: 'fb-05', front: 'famille', back: { en: 'family', fr: 'famille', ko: '가족', ja: '家族' }, pronunciation: 'fah-MEE-yuh' },
      { id: 'fb-06', front: 'ami', back: { en: 'friend', fr: 'ami', ko: '친구', ja: '友達' }, pronunciation: 'ah-MEE' },
      { id: 'fb-07', front: 'soleil', back: { en: 'sun', fr: 'soleil', ko: '태양', ja: '太陽' }, pronunciation: 'soh-LAY' },
      { id: 'fb-08', front: 'eau', back: { en: 'water', fr: 'eau', ko: '물', ja: '水' }, pronunciation: 'oh' },
      { id: 'fb-09', front: 'musique', back: { en: 'music', fr: 'musique', ko: '음악', ja: '音楽' }, pronunciation: 'mew-ZEEK' },
      { id: 'fb-10', front: 'livre', back: { en: 'book', fr: 'livre', ko: '책', ja: '本' }, pronunciation: 'LEE-vruh' },
      { id: 'fb-11', front: 'fleur', back: { en: 'flower', fr: 'fleur', ko: '꽃', ja: '花' }, pronunciation: 'fluhr' },
      { id: 'fb-12', front: 'temps', back: { en: 'time/weather', fr: 'temps', ko: '시간/날씨', ja: '時間/天気' }, pronunciation: 'tahn' },
      { id: 'fb-13', front: 'école', back: { en: 'school', fr: 'école', ko: '학교', ja: '学校' }, pronunciation: 'ay-KOL' },
      { id: 'fb-14', front: 'travail', back: { en: 'work', fr: 'travail', ko: '일', ja: '仕事' }, pronunciation: 'trah-VIE' },
      { id: 'fb-15', front: 'bonheur', back: { en: 'happiness', fr: 'bonheur', ko: '행복', ja: '幸福' }, pronunciation: 'bohn-UHR' },
      { id: 'fb-c01', noteType: 'Cloze', front: '_____, comment allez-vous?', back: { en: 'hello', fr: 'bonjour', ko: '안녕하세요', ja: 'こんにちは' }, pronunciation: 'hello', extra: 'Bonjour, comment allez-vous?' },
      { id: 'fb-c02', noteType: 'Cloze', front: '_____ beaucoup pour votre aide.', back: { en: 'thank you', fr: 'merci', ko: '감사합니다', ja: 'ありがとう' }, pronunciation: 'thank you', extra: 'Merci beaucoup pour votre aide.' },
      { id: 'fb-c03', noteType: 'Cloze', front: 'Ma _____ est très grande.', back: { en: 'family', fr: 'famille', ko: '가족', ja: '家族' }, pronunciation: 'family', extra: 'Ma famille est très grande.' },
      { id: 'fb-c04', noteType: 'Cloze', front: 'Le _____ brille aujourd\'hui.', back: { en: 'sun', fr: 'soleil', ko: '태양', ja: '太陽' }, pronunciation: 'sun', extra: "Le soleil brille aujourd'hui." },
      { id: 'fb-c05', noteType: 'Cloze', front: 'J\'aime écouter de la _____.', back: { en: 'music', fr: 'musique', ko: '음악', ja: '音楽' }, pronunciation: 'music', extra: "J'aime écouter de la musique." },
    ],
  },
  {
    id: 'french-food',
    lang: 'fr',
    name: 'French Cuisine',
    nameLocal: 'Cuisine française',
    description: 'Delicious French food vocabulary — croissant, baguette, crème brûlée and more.',
    emoji: '🥐',
    accentColor: '#b45309',
    cards: [
      { id: 'ff-01', front: 'croissant', back: { en: 'crescent pastry', fr: 'croissant', ko: '크루아상', ja: 'クロワッサン' }, pronunciation: 'kwah-SAHN' },
      { id: 'ff-02', front: 'baguette', back: { en: 'French bread', fr: 'baguette', ko: '바게트', ja: 'バゲット' }, pronunciation: 'bah-GET' },
      { id: 'ff-03', front: 'fromage', back: { en: 'cheese', fr: 'fromage', ko: '치즈', ja: 'チーズ' }, pronunciation: 'froh-MAHZH' },
      { id: 'ff-04', front: 'vin', back: { en: 'wine', fr: 'vin', ko: '와인', ja: 'ワイン' }, pronunciation: 'vahn' },
      { id: 'ff-05', front: 'beurre', back: { en: 'butter', fr: 'beurre', ko: '버터', ja: 'バター' }, pronunciation: 'buhr' },
      { id: 'ff-06', front: 'crêpe', back: { en: 'thin pancake', fr: 'crêpe', ko: '크레이프', ja: 'クレープ' }, pronunciation: 'krep' },
      { id: 'ff-07', front: 'soupe', back: { en: 'soup', fr: 'soupe', ko: '수프', ja: 'スープ' }, pronunciation: 'soop' },
      { id: 'ff-08', front: 'salade', back: { en: 'salad', fr: 'salade', ko: '샐러드', ja: 'サラダ' }, pronunciation: 'sah-LAHD' },
      { id: 'ff-09', front: 'dessert', back: { en: 'dessert', fr: 'dessert', ko: '디저트', ja: 'デザート' }, pronunciation: 'deh-SAIR' },
      { id: 'ff-10', front: 'pâtisserie', back: { en: 'pastry shop', fr: 'pâtisserie', ko: '제과점', ja: 'パティスリー' }, pronunciation: 'pah-tee-suh-REE' },
      { id: 'ff-11', front: 'poulet', back: { en: 'chicken', fr: 'poulet', ko: '닭고기', ja: '鶏肉' }, pronunciation: 'poo-LAY' },
      { id: 'ff-12', front: 'poisson', back: { en: 'fish', fr: 'poisson', ko: '생선', ja: '魚' }, pronunciation: 'pwah-SOHN' },
      { id: 'ff-13', front: 'café', back: { en: 'coffee', fr: 'café', ko: '커피', ja: 'コーヒー' }, pronunciation: 'kah-FAY' },
      { id: 'ff-14', front: 'boulangerie', back: { en: 'bakery', fr: 'boulangerie', ko: '빵집', ja: 'パン屋' }, pronunciation: 'boo-lahnzh-REE' },
      { id: 'ff-15', front: 'recette', back: { en: 'recipe', fr: 'recette', ko: '레시피', ja: 'レシピ' }, pronunciation: 'ruh-SET' },
      { id: 'ff-c01', noteType: 'Cloze', front: 'Je voudrais un _____ au beurre.', back: { en: 'croissant', fr: 'croissant', ko: '크루아상', ja: 'クロワッサン' }, pronunciation: 'croissant', extra: 'Je voudrais un croissant au beurre.' },
      { id: 'ff-c02', noteType: 'Cloze', front: 'La France est célèbre pour son _____.', back: { en: 'cheese', fr: 'fromage', ko: '치즈', ja: 'チーズ' }, pronunciation: 'cheese', extra: 'La France est célèbre pour son fromage.' },
      { id: 'ff-c03', noteType: 'Cloze', front: 'Un _____ rouge, s\'il vous plaît.', back: { en: 'wine', fr: 'vin', ko: '와인', ja: 'ワイン' }, pronunciation: 'wine', extra: "Un vin rouge, s'il vous plaît." },
      { id: 'ff-c04', noteType: 'Cloze', front: 'J\'achète du pain à la _____.', back: { en: 'bakery', fr: 'boulangerie', ko: '빵집', ja: 'パン屋' }, pronunciation: 'bakery', extra: "J'achète du pain à la boulangerie." },
      { id: 'ff-c05', noteType: 'Cloze', front: 'Un _____ avec du lait, s\'il vous plaît.', back: { en: 'coffee', fr: 'café', ko: '커피', ja: 'コーヒー' }, pronunciation: 'coffee', extra: "Un café avec du lait, s'il vous plaît." },
    ],
  },
  {
    id: 'french-travel',
    lang: 'fr',
    name: 'French Travel',
    nameLocal: 'Voyage en français',
    description: 'Essential French phrases and vocabulary for traveling in France.',
    emoji: '✈️',
    accentColor: '#0369a1',
    cards: [
      { id: 'ft-01', front: 'billet', back: { en: 'ticket', fr: 'billet', ko: '표', ja: '切符' }, pronunciation: 'bee-YAY' },
      { id: 'ft-02', front: 'hôtel', back: { en: 'hotel', fr: 'hôtel', ko: '호텔', ja: 'ホテル' }, pronunciation: 'oh-TEL' },
      { id: 'ft-03', front: 'gare', back: { en: 'train station', fr: 'gare', ko: '기차역', ja: '駅' }, pronunciation: 'gahr' },
      { id: 'ft-04', front: 'aéroport', back: { en: 'airport', fr: 'aéroport', ko: '공항', ja: '空港' }, pronunciation: 'ah-ay-roh-POR' },
      { id: 'ft-05', front: 'passeport', back: { en: 'passport', fr: 'passeport', ko: '여권', ja: 'パスポート' }, pronunciation: 'pahs-POR' },
      { id: 'ft-06', front: 'valise', back: { en: 'suitcase', fr: 'valise', ko: '여행가방', ja: 'スーツケース' }, pronunciation: 'vah-LEEZ' },
      { id: 'ft-07', front: 'musée', back: { en: 'museum', fr: 'musée', ko: '박물관', ja: '美術館' }, pronunciation: 'mew-ZAY' },
      { id: 'ft-08', front: 'pharmacie', back: { en: 'pharmacy', fr: 'pharmacie', ko: '약국', ja: '薬局' }, pronunciation: 'far-mah-SEE' },
      { id: 'ft-09', front: 'plan', back: { en: 'map', fr: 'plan', ko: '지도', ja: '地図' }, pronunciation: 'plahn' },
      { id: 'ft-10', front: 'monnaie', back: { en: 'currency/change', fr: 'monnaie', ko: '화폐/잔돈', ja: '通貨/おつり' }, pronunciation: 'moh-NAY' },
      { id: 'ft-11', front: 'sortie', back: { en: 'exit', fr: 'sortie', ko: '출구', ja: '出口' }, pronunciation: 'sor-TEE' },
      { id: 'ft-12', front: 'entrée', back: { en: 'entrance', fr: 'entrée', ko: '입구', ja: '入口' }, pronunciation: 'ahn-TRAY' },
      { id: 'ft-13', front: 'métro', back: { en: 'subway', fr: 'métro', ko: '지하철', ja: '地下鉄' }, pronunciation: 'may-TROH' },
      { id: 'ft-14', front: 'quartier', back: { en: 'neighborhood', fr: 'quartier', ko: '동네', ja: '地区' }, pronunciation: 'kar-TYAY' },
      { id: 'ft-15', front: 'souvenir', back: { en: 'souvenir', fr: 'souvenir', ko: '기념품', ja: 'お土産' }, pronunciation: 'soov-NEER' },
      { id: 'ft-c01', noteType: 'Cloze', front: 'Où est la _____, s\'il vous plaît?', back: { en: 'train station', fr: 'gare', ko: '기차역', ja: '駅' }, pronunciation: 'train station', extra: "Où est la gare, s'il vous plaît?" },
      { id: 'ft-c02', noteType: 'Cloze', front: 'J\'ai réservé un _____ pour ce soir.', back: { en: 'hotel', fr: 'hôtel', ko: '호텔', ja: 'ホテル' }, pronunciation: 'hotel', extra: "J'ai réservé un hôtel pour ce soir." },
      { id: 'ft-c03', noteType: 'Cloze', front: 'Je prends le _____ pour aller au musée.', back: { en: 'subway', fr: 'métro', ko: '지하철', ja: '地下鉄' }, pronunciation: 'subway', extra: 'Je prends le métro pour aller au musée.' },
      { id: 'ft-c04', noteType: 'Cloze', front: 'N\'oubliez pas votre _____.', back: { en: 'passport', fr: 'passeport', ko: '여권', ja: 'パスポート' }, pronunciation: 'passport', extra: "N'oubliez pas votre passeport." },
      { id: 'ft-c05', noteType: 'Cloze', front: 'Nous allons visiter le _____ du Louvre.', back: { en: 'museum', fr: 'musée', ko: '박물관', ja: '美術館' }, pronunciation: 'museum', extra: 'Nous allons visiter le musée du Louvre.' },
    ],
  },
  // ─── Spanish Decks ─────────────────────────────────────────────────
  {
    id: 'spanish-basics',
    lang: 'es',
    name: 'Spanish Basics',
    nameLocal: 'Español básico',
    description: 'Essential everyday Spanish vocabulary — perfect for beginners.',
    emoji: '🇪🇸',
    accentColor: '#dc2626',
    cards: [
      { id: 'sb-01', front: 'hola', back: { en: 'hello', es: 'hola', ko: '안녕하세요', ja: 'こんにちは' }, pronunciation: 'OH-lah' },
      { id: 'sb-02', front: 'gracias', back: { en: 'thank you', es: 'gracias', ko: '감사합니다', ja: 'ありがとう' }, pronunciation: 'GRAH-see-ahs' },
      { id: 'sb-03', front: 'amor', back: { en: 'love', es: 'amor', ko: '사랑', ja: '愛' }, pronunciation: 'ah-MOR' },
      { id: 'sb-04', front: 'casa', back: { en: 'house', es: 'casa', ko: '집', ja: '家' }, pronunciation: 'KAH-sah' },
      { id: 'sb-05', front: 'familia', back: { en: 'family', es: 'familia', ko: '가족', ja: '家族' }, pronunciation: 'fah-MEE-lee-ah' },
      { id: 'sb-06', front: 'amigo', back: { en: 'friend', es: 'amigo', ko: '친구', ja: '友達' }, pronunciation: 'ah-MEE-goh' },
      { id: 'sb-07', front: 'sol', back: { en: 'sun', es: 'sol', ko: '태양', ja: '太陽' }, pronunciation: 'sohl' },
      { id: 'sb-08', front: 'agua', back: { en: 'water', es: 'agua', ko: '물', ja: '水' }, pronunciation: 'AH-gwah' },
      { id: 'sb-09', front: 'comida', back: { en: 'food', es: 'comida', ko: '음식', ja: '食べ物' }, pronunciation: 'koh-MEE-dah' },
      { id: 'sb-10', front: 'libro', back: { en: 'book', es: 'libro', ko: '책', ja: '本' }, pronunciation: 'LEE-broh' },
      { id: 'sb-11', front: 'tiempo', back: { en: 'time/weather', es: 'tiempo', ko: '시간/날씨', ja: '時間/天気' }, pronunciation: 'tee-EM-poh' },
      { id: 'sb-12', front: 'escuela', back: { en: 'school', es: 'escuela', ko: '학교', ja: '学校' }, pronunciation: 'es-KWEH-lah' },
      { id: 'sb-13', front: 'trabajo', back: { en: 'work', es: 'trabajo', ko: '일', ja: '仕事' }, pronunciation: 'trah-BAH-hoh' },
      { id: 'sb-14', front: 'felicidad', back: { en: 'happiness', es: 'felicidad', ko: '행복', ja: '幸福' }, pronunciation: 'feh-lee-see-DAHD' },
      { id: 'sb-15', front: 'corazón', back: { en: 'heart', es: 'corazón', ko: '마음', ja: '心' }, pronunciation: 'koh-rah-SOHN' },
      { id: 'sb-c01', noteType: 'Cloze', front: '_____, ¿cómo estás?', back: { en: 'hello', es: 'hola', ko: '안녕하세요', ja: 'こんにちは' }, pronunciation: 'hello', extra: 'Hola, ¿cómo estás?' },
      { id: 'sb-c02', noteType: 'Cloze', front: '_____ por tu ayuda.', back: { en: 'thank you', es: 'gracias', ko: '감사합니다', ja: 'ありがとう' }, pronunciation: 'thank you', extra: 'Gracias por tu ayuda.' },
      { id: 'sb-c03', noteType: 'Cloze', front: 'Mi _____ es muy grande.', back: { en: 'family', es: 'familia', ko: '가족', ja: '家族' }, pronunciation: 'family', extra: 'Mi familia es muy grande.' },
      { id: 'sb-c04', noteType: 'Cloze', front: 'El _____ brilla mucho hoy.', back: { en: 'sun', es: 'sol', ko: '태양', ja: '太陽' }, pronunciation: 'sun', extra: 'El sol brilla mucho hoy.' },
      { id: 'sb-c05', noteType: 'Cloze', front: 'Mi mejor _____ vive en Madrid.', back: { en: 'friend', es: 'amigo', ko: '친구', ja: '友達' }, pronunciation: 'friend', extra: 'Mi mejor amigo vive en Madrid.' },
    ],
  },
  {
    id: 'spanish-food',
    lang: 'es',
    name: 'Spanish Cuisine',
    nameLocal: 'Cocina española',
    description: 'Delicious Spanish food vocabulary — paella, tapas, churros and more.',
    emoji: '🥘',
    accentColor: '#c2410c',
    cards: [
      { id: 'sf-01', front: 'paella', back: { en: 'rice dish', es: 'paella', ko: '빠에야', ja: 'パエリア' }, pronunciation: 'pah-EH-yah' },
      { id: 'sf-02', front: 'tapas', back: { en: 'small dishes', es: 'tapas', ko: '타파스', ja: 'タパス' }, pronunciation: 'TAH-pahs' },
      { id: 'sf-03', front: 'churros', back: { en: 'fried dough pastry', es: 'churros', ko: '츄러스', ja: 'チュロス' }, pronunciation: 'CHOO-rohs' },
      { id: 'sf-04', front: 'tortilla', back: { en: 'Spanish omelette', es: 'tortilla', ko: '토르티야', ja: 'トルティーヤ' }, pronunciation: 'tor-TEE-yah' },
      { id: 'sf-05', front: 'jamón', back: { en: 'ham', es: 'jamón', ko: '하몽', ja: 'ハモン' }, pronunciation: 'hah-MOHN' },
      { id: 'sf-06', front: 'aceite', back: { en: 'oil', es: 'aceite', ko: '기름', ja: '油' }, pronunciation: 'ah-SAY-tay' },
      { id: 'sf-07', front: 'queso', back: { en: 'cheese', es: 'queso', ko: '치즈', ja: 'チーズ' }, pronunciation: 'KAY-soh' },
      { id: 'sf-08', front: 'pan', back: { en: 'bread', es: 'pan', ko: '빵', ja: 'パン' }, pronunciation: 'pahn' },
      { id: 'sf-09', front: 'vino', back: { en: 'wine', es: 'vino', ko: '와인', ja: 'ワイン' }, pronunciation: 'VEE-noh' },
      { id: 'sf-10', front: 'cerveza', back: { en: 'beer', es: 'cerveza', ko: '맥주', ja: 'ビール' }, pronunciation: 'ser-VAY-sah' },
      { id: 'sf-11', front: 'gazpacho', back: { en: 'cold tomato soup', es: 'gazpacho', ko: '가스파초', ja: 'ガスパチョ' }, pronunciation: 'gahz-PAH-choh' },
      { id: 'sf-12', front: 'sangría', back: { en: 'wine punch', es: 'sangría', ko: '상그리아', ja: 'サングリア' }, pronunciation: 'sahn-GREE-ah' },
      { id: 'sf-13', front: 'arroz', back: { en: 'rice', es: 'arroz', ko: '쌀', ja: '米' }, pronunciation: 'ah-ROHS' },
      { id: 'sf-14', front: 'marisco', back: { en: 'seafood', es: 'marisco', ko: '해산물', ja: 'シーフード' }, pronunciation: 'mah-REES-koh' },
      { id: 'sf-15', front: 'flan', back: { en: 'caramel custard', es: 'flan', ko: '플란', ja: 'プリン' }, pronunciation: 'flahn' },
      { id: 'sf-c01', noteType: 'Cloze', front: 'La _____ es un plato típico de Valencia.', back: { en: 'paella', es: 'paella', ko: '빠에야', ja: 'パエリア' }, pronunciation: 'paella', extra: 'La paella es un plato típico de Valencia.' },
      { id: 'sf-c02', noteType: 'Cloze', front: 'Vamos a comer _____ en el bar.', back: { en: 'tapas', es: 'tapas', ko: '타파스', ja: 'タパス' }, pronunciation: 'tapas', extra: 'Vamos a comer tapas en el bar.' },
      { id: 'sf-c03', noteType: 'Cloze', front: 'Una _____ tinto, por favor.', back: { en: 'wine', es: 'vino', ko: '와인', ja: 'ワイン' }, pronunciation: 'wine', extra: 'Un vino tinto, por favor.' },
      { id: 'sf-c04', noteType: 'Cloze', front: 'El _____ ibérico es muy famoso.', back: { en: 'ham', es: 'jamón', ko: '하몽', ja: 'ハモン' }, pronunciation: 'ham', extra: 'El jamón ibérico es muy famoso.' },
      { id: 'sf-c05', noteType: 'Cloze', front: 'De postre, quiero un _____.', back: { en: 'caramel custard', es: 'flan', ko: '플란', ja: 'プリン' }, pronunciation: 'flan', extra: 'De postre, quiero un flan.' },
    ],
  },
  {
    id: 'spanish-travel',
    lang: 'es',
    name: 'Spanish Travel',
    nameLocal: 'Viaje en español',
    description: 'Essential Spanish vocabulary for traveling in Spanish-speaking countries.',
    emoji: '🌎',
    accentColor: '#047857',
    cards: [
      { id: 'st-01', front: 'aeropuerto', back: { en: 'airport', es: 'aeropuerto', ko: '공항', ja: '空港' }, pronunciation: 'ah-eh-roh-PWEHR-toh' },
      { id: 'st-02', front: 'hotel', back: { en: 'hotel', es: 'hotel', ko: '호텔', ja: 'ホテル' }, pronunciation: 'oh-TEL' },
      { id: 'st-03', front: 'estación', back: { en: 'station', es: 'estación', ko: '역', ja: '駅' }, pronunciation: 'es-tah-see-OHN' },
      { id: 'st-04', front: 'billete', back: { en: 'ticket', es: 'billete', ko: '표', ja: '切符' }, pronunciation: 'bee-YEH-tay' },
      { id: 'st-05', front: 'pasaporte', back: { en: 'passport', es: 'pasaporte', ko: '여권', ja: 'パスポート' }, pronunciation: 'pah-sah-POR-tay' },
      { id: 'st-06', front: 'maleta', back: { en: 'suitcase', es: 'maleta', ko: '여행가방', ja: 'スーツケース' }, pronunciation: 'mah-LAY-tah' },
      { id: 'st-07', front: 'playa', back: { en: 'beach', es: 'playa', ko: '해변', ja: 'ビーチ' }, pronunciation: 'PLAH-yah' },
      { id: 'st-08', front: 'museo', back: { en: 'museum', es: 'museo', ko: '박물관', ja: '美術館' }, pronunciation: 'moo-SAY-oh' },
      { id: 'st-09', front: 'mapa', back: { en: 'map', es: 'mapa', ko: '지도', ja: '地図' }, pronunciation: 'MAH-pah' },
      { id: 'st-10', front: 'dinero', back: { en: 'money', es: 'dinero', ko: '돈', ja: 'お金' }, pronunciation: 'dee-NEH-roh' },
      { id: 'st-11', front: 'salida', back: { en: 'exit', es: 'salida', ko: '출구', ja: '出口' }, pronunciation: 'sah-LEE-dah' },
      { id: 'st-12', front: 'entrada', back: { en: 'entrance', es: 'entrada', ko: '입구', ja: '入口' }, pronunciation: 'en-TRAH-dah' },
      { id: 'st-13', front: 'recuerdo', back: { en: 'souvenir', es: 'recuerdo', ko: '기념품', ja: 'お土産' }, pronunciation: 'reh-KWER-doh' },
      { id: 'st-14', front: 'equipaje', back: { en: 'luggage', es: 'equipaje', ko: '짐', ja: '荷物' }, pronunciation: 'eh-kee-PAH-hay' },
      { id: 'st-15', front: 'reserva', back: { en: 'reservation', es: 'reserva', ko: '예약', ja: '予約' }, pronunciation: 'reh-SEHR-vah' },
      { id: 'st-c01', noteType: 'Cloze', front: '¿Dónde está el _____?', back: { en: 'airport', es: 'aeropuerto', ko: '공항', ja: '空港' }, pronunciation: 'airport', extra: '¿Dónde está el aeropuerto?' },
      { id: 'st-c02', noteType: 'Cloze', front: 'Tengo una _____ en el hotel.', back: { en: 'reservation', es: 'reserva', ko: '예약', ja: '予約' }, pronunciation: 'reservation', extra: 'Tengo una reserva en el hotel.' },
      { id: 'st-c03', noteType: 'Cloze', front: 'No olvides tu _____.', back: { en: 'passport', es: 'pasaporte', ko: '여권', ja: 'パスポート' }, pronunciation: 'passport', extra: 'No olvides tu pasaporte.' },
      { id: 'st-c04', noteType: 'Cloze', front: 'Vamos a la _____ esta tarde.', back: { en: 'beach', es: 'playa', ko: '해변', ja: 'ビーチ' }, pronunciation: 'beach', extra: 'Vamos a la playa esta tarde.' },
      { id: 'st-c05', noteType: 'Cloze', front: 'Compré un _____ para mi madre.', back: { en: 'souvenir', es: 'recuerdo', ko: '기념품', ja: 'お土産' }, pronunciation: 'souvenir', extra: 'Compré un recuerdo para mi madre.' },
    ],
  },
  // ─── Chinese Decks ─────────────────────────────────────────────────
  {
    id: 'chinese-basics',
    lang: 'zh',
    name: 'Chinese Basics',
    nameLocal: '中文基础',
    description: 'Essential everyday Chinese vocabulary — perfect for beginners.',
    emoji: '🇨🇳',
    accentColor: '#dc2626',
    cards: [
      { id: 'cb-01', front: '你好', back: { en: 'hello', zh: '你好', ko: '안녕하세요', ja: 'こんにちは' }, pronunciation: 'nǐ hǎo' },
      { id: 'cb-02', front: '谢谢', back: { en: 'thank you', zh: '谢谢', ko: '감사합니다', ja: 'ありがとう' }, pronunciation: 'xiè xie' },
      { id: 'cb-03', front: '爱', back: { en: 'love', zh: '爱', ko: '사랑', ja: '愛' }, pronunciation: 'ài' },
      { id: 'cb-04', front: '家', back: { en: 'home/family', zh: '家', ko: '집/가족', ja: '家' }, pronunciation: 'jiā' },
      { id: 'cb-05', front: '朋友', back: { en: 'friend', zh: '朋友', ko: '친구', ja: '友達' }, pronunciation: 'péng yǒu' },
      { id: 'cb-06', front: '学校', back: { en: 'school', zh: '学校', ko: '학교', ja: '学校' }, pronunciation: 'xué xiào' },
      { id: 'cb-07', front: '水', back: { en: 'water', zh: '水', ko: '물', ja: '水' }, pronunciation: 'shuǐ' },
      { id: 'cb-08', front: '太阳', back: { en: 'sun', zh: '太阳', ko: '태양', ja: '太陽' }, pronunciation: 'tài yáng' },
      { id: 'cb-09', front: '音乐', back: { en: 'music', zh: '音乐', ko: '음악', ja: '音楽' }, pronunciation: 'yīn yuè' },
      { id: 'cb-10', front: '书', back: { en: 'book', zh: '书', ko: '책', ja: '本' }, pronunciation: 'shū' },
      { id: 'cb-11', front: '时间', back: { en: 'time', zh: '时间', ko: '시간', ja: '時間' }, pronunciation: 'shí jiān' },
      { id: 'cb-12', front: '快乐', back: { en: 'happy', zh: '快乐', ko: '즐거운', ja: '楽しい' }, pronunciation: 'kuài lè' },
      { id: 'cb-13', front: '花', back: { en: 'flower', zh: '花', ko: '꽃', ja: '花' }, pronunciation: 'huā' },
      { id: 'cb-14', front: '梦', back: { en: 'dream', zh: '梦', ko: '꿈', ja: '夢' }, pronunciation: 'mèng' },
      { id: 'cb-15', front: '天空', back: { en: 'sky', zh: '天空', ko: '하늘', ja: '空' }, pronunciation: 'tiān kōng' },
      { id: 'cb-c01', noteType: 'Cloze', front: '_____, 你叫什么名字?', back: { en: 'hello', zh: '你好', ko: '안녕하세요', ja: 'こんにちは' }, pronunciation: 'hello', extra: '你好, 你叫什么名字?' },
      { id: 'cb-c02', noteType: 'Cloze', front: '_____, 你帮了我很多。', back: { en: 'thank you', zh: '谢谢', ko: '감사합니다', ja: 'ありがとう' }, pronunciation: 'thank you', extra: '谢谢, 你帮了我很多。' },
      { id: 'cb-c03', noteType: 'Cloze', front: '我的_____是最棒的。', back: { en: 'friend', zh: '朋友', ko: '친구', ja: '友達' }, pronunciation: 'friend', extra: '我的朋友是最棒的。' },
      { id: 'cb-c04', noteType: 'Cloze', front: '我喜欢听_____.', back: { en: 'music', zh: '音乐', ko: '음악', ja: '音楽' }, pronunciation: 'music', extra: '我喜欢听音乐.' },
      { id: 'cb-c05', noteType: 'Cloze', front: '今天的_____很蓝。', back: { en: 'sky', zh: '天空', ko: '하늘', ja: '空' }, pronunciation: 'sky', extra: '今天的天空很蓝。' },
    ],
  },
  {
    id: 'chinese-food',
    lang: 'zh',
    name: 'Chinese Cuisine',
    nameLocal: '中国美食',
    description: 'Popular Chinese food vocabulary — dumplings, noodles, dim sum and more.',
    emoji: '🥟',
    accentColor: '#b91c1c',
    cards: [
      { id: 'cf-01', front: '饺子', back: { en: 'dumplings', zh: '饺子', ko: '만두', ja: '餃子' }, pronunciation: 'jiǎo zi' },
      { id: 'cf-02', front: '面条', back: { en: 'noodles', zh: '面条', ko: '국수', ja: '麺' }, pronunciation: 'miàn tiáo' },
      { id: 'cf-03', front: '米饭', back: { en: 'rice', zh: '米饭', ko: '밥', ja: 'ご飯' }, pronunciation: 'mǐ fàn' },
      { id: 'cf-04', front: '火锅', back: { en: 'hot pot', zh: '火锅', ko: '훠궈', ja: '火鍋' }, pronunciation: 'huǒ guō' },
      { id: 'cf-05', front: '点心', back: { en: 'dim sum', zh: '点心', ko: '딤섬', ja: '点心' }, pronunciation: 'diǎn xin' },
      { id: 'cf-06', front: '豆腐', back: { en: 'tofu', zh: '豆腐', ko: '두부', ja: '豆腐' }, pronunciation: 'dòu fu' },
      { id: 'cf-07', front: '茶', back: { en: 'tea', zh: '茶', ko: '차', ja: 'お茶' }, pronunciation: 'chá' },
      { id: 'cf-08', front: '包子', back: { en: 'steamed bun', zh: '包子', ko: '바오쯔', ja: '肉まん' }, pronunciation: 'bāo zi' },
      { id: 'cf-09', front: '炒饭', back: { en: 'fried rice', zh: '炒饭', ko: '볶음밥', ja: 'チャーハン' }, pronunciation: 'chǎo fàn' },
      { id: 'cf-10', front: '酱油', back: { en: 'soy sauce', zh: '酱油', ko: '간장', ja: '醤油' }, pronunciation: 'jiàng yóu' },
      { id: 'cf-11', front: '月饼', back: { en: 'mooncake', zh: '月饼', ko: '월병', ja: '月餅' }, pronunciation: 'yuè bǐng' },
      { id: 'cf-12', front: '春卷', back: { en: 'spring roll', zh: '春卷', ko: '춘권', ja: '春巻き' }, pronunciation: 'chūn juǎn' },
      { id: 'cf-13', front: '烤鸭', back: { en: 'roast duck', zh: '烤鸭', ko: '카오야', ja: '北京ダック' }, pronunciation: 'kǎo yā' },
      { id: 'cf-14', front: '筷子', back: { en: 'chopsticks', zh: '筷子', ko: '젓가락', ja: 'お箸' }, pronunciation: 'kuài zi' },
      { id: 'cf-15', front: '饭店', back: { en: 'restaurant', zh: '饭店', ko: '식당', ja: 'レストラン' }, pronunciation: 'fàn diàn' },
      { id: 'cf-c01', noteType: 'Cloze', front: '我最喜欢吃_____.', back: { en: 'dumplings', zh: '饺子', ko: '만두', ja: '餃子' }, pronunciation: 'dumplings', extra: '我最喜欢吃饺子.' },
      { id: 'cf-c02', noteType: 'Cloze', front: '冬天要吃_____才暖和。', back: { en: 'hot pot', zh: '火锅', ko: '훠궈', ja: '火鍋' }, pronunciation: 'hot pot', extra: '冬天要吃火锅才暖和。' },
      { id: 'cf-c03', noteType: 'Cloze', front: '请给我一杯_____.', back: { en: 'tea', zh: '茶', ko: '차', ja: 'お茶' }, pronunciation: 'tea', extra: '请给我一杯茶.' },
      { id: 'cf-c04', noteType: 'Cloze', front: '北京_____非常有名。', back: { en: 'roast duck', zh: '烤鸭', ko: '카오야', ja: '北京ダック' }, pronunciation: 'roast duck', extra: '北京烤鸭非常有名。' },
      { id: 'cf-c05', noteType: 'Cloze', front: '你会用_____吃饭吗?', back: { en: 'chopsticks', zh: '筷子', ko: '젓가락', ja: 'お箸' }, pronunciation: 'chopsticks', extra: '你会用筷子吃饭吗?' },
    ],
  },
  {
    id: 'chinese-culture',
    lang: 'zh',
    name: 'Chinese Culture',
    nameLocal: '中国文化',
    description: 'Chinese culture vocabulary — Spring Festival, dragon, kung fu and more.',
    emoji: '🏯',
    accentColor: '#9f1239',
    cards: [
      { id: 'cc-01', front: '春节', back: { en: 'Spring Festival', zh: '春节', ko: '춘절', ja: '春節' }, pronunciation: 'chūn jié' },
      { id: 'cc-02', front: '龙', back: { en: 'dragon', zh: '龙', ko: '용', ja: '龍' }, pronunciation: 'lóng' },
      { id: 'cc-03', front: '功夫', back: { en: 'kung fu', zh: '功夫', ko: '쿵푸', ja: 'カンフー' }, pronunciation: 'gōng fu' },
      { id: 'cc-04', front: '熊猫', back: { en: 'panda', zh: '熊猫', ko: '판다', ja: 'パンダ' }, pronunciation: 'xióng māo' },
      { id: 'cc-05', front: '长城', back: { en: 'Great Wall', zh: '长城', ko: '만리장성', ja: '万里の長城' }, pronunciation: 'cháng chéng' },
      { id: 'cc-06', front: '红包', back: { en: 'red envelope', zh: '红包', ko: '홍바오', ja: 'お年玉袋' }, pronunciation: 'hóng bāo' },
      { id: 'cc-07', front: '书法', back: { en: 'calligraphy', zh: '书法', ko: '서예', ja: '書道' }, pronunciation: 'shū fǎ' },
      { id: 'cc-08', front: '太极', back: { en: 'tai chi', zh: '太极', ko: '태극', ja: '太極' }, pronunciation: 'tài jí' },
      { id: 'cc-09', front: '灯笼', back: { en: 'lantern', zh: '灯笼', ko: '등불', ja: 'ランタン' }, pronunciation: 'dēng long' },
      { id: 'cc-10', front: '丝绸', back: { en: 'silk', zh: '丝绸', ko: '비단', ja: 'シルク' }, pronunciation: 'sī chóu' },
      { id: 'cc-11', front: '瓷器', back: { en: 'porcelain', zh: '瓷器', ko: '도자기', ja: '磁器' }, pronunciation: 'cí qì' },
      { id: 'cc-12', front: '中秋节', back: { en: 'Mid-Autumn Festival', zh: '中秋节', ko: '중추절', ja: '中秋節' }, pronunciation: 'zhōng qiū jié' },
      { id: 'cc-13', front: '京剧', back: { en: 'Peking opera', zh: '京剧', ko: '경극', ja: '京劇' }, pronunciation: 'jīng jù' },
      { id: 'cc-14', front: '故宫', back: { en: 'Forbidden City', zh: '故宫', ko: '자금성', ja: '故宮' }, pronunciation: 'gù gōng' },
      { id: 'cc-15', front: '筷子', back: { en: 'chopsticks', zh: '筷子', ko: '젓가락', ja: 'お箸' }, pronunciation: 'kuài zi' },
      { id: 'cc-c01', noteType: 'Cloze', front: '_____是中国最重要的节日。', back: { en: 'Spring Festival', zh: '春节', ko: '춘절', ja: '春節' }, pronunciation: 'Spring Festival', extra: '春节是中国最重要的节日。' },
      { id: 'cc-c02', noteType: 'Cloze', front: '中国人称自己为_____的传人。', back: { en: 'dragon', zh: '龙', ko: '용', ja: '龍' }, pronunciation: 'dragon', extra: '中国人称自己为龙的传人。' },
      { id: 'cc-c03', noteType: 'Cloze', front: '过年的时候要发_____.', back: { en: 'red envelope', zh: '红包', ko: '홍바오', ja: 'お年玉袋' }, pronunciation: 'red envelope', extra: '过年的时候要发红包.' },
      { id: 'cc-c04', noteType: 'Cloze', front: '爷爷每天早上打_____.', back: { en: 'tai chi', zh: '太极', ko: '태극', ja: '太極' }, pronunciation: 'tai chi', extra: '爷爷每天早上打太极.' },
      { id: 'cc-c05', noteType: 'Cloze', front: '我想去看一看_____.', back: { en: 'Great Wall', zh: '长城', ko: '만리장성', ja: '万里の長城' }, pronunciation: 'Great Wall', extra: '我想去看一看长城.' },
    ],
  },
  // ─── German Decks ──────────────────────────────────────────────────
  {
    id: 'german-basics',
    lang: 'de',
    name: 'German Basics',
    nameLocal: 'Deutsch Grundlagen',
    description: 'Essential everyday German vocabulary — perfect for beginners.',
    emoji: '🇩🇪',
    accentColor: '#1e3a5f',
    cards: [
      { id: 'gb-01', front: 'Hallo', back: { en: 'hello', de: 'Hallo', ko: '안녕하세요', ja: 'こんにちは' }, pronunciation: 'HAH-loh' },
      { id: 'gb-02', front: 'Danke', back: { en: 'thank you', de: 'Danke', ko: '감사합니다', ja: 'ありがとう' }, pronunciation: 'DAHN-kuh' },
      { id: 'gb-03', front: 'Liebe', back: { en: 'love', de: 'Liebe', ko: '사랑', ja: '愛' }, pronunciation: 'LEE-buh' },
      { id: 'gb-04', front: 'Haus', back: { en: 'house', de: 'Haus', ko: '집', ja: '家' }, pronunciation: 'hows' },
      { id: 'gb-05', front: 'Familie', back: { en: 'family', de: 'Familie', ko: '가족', ja: '家族' }, pronunciation: 'fah-MEE-lee-uh' },
      { id: 'gb-06', front: 'Freund', back: { en: 'friend', de: 'Freund', ko: '친구', ja: '友達' }, pronunciation: 'froynt' },
      { id: 'gb-07', front: 'Sonne', back: { en: 'sun', de: 'Sonne', ko: '태양', ja: '太陽' }, pronunciation: 'ZON-nuh' },
      { id: 'gb-08', front: 'Wasser', back: { en: 'water', de: 'Wasser', ko: '물', ja: '水' }, pronunciation: 'VAH-ser' },
      { id: 'gb-09', front: 'Musik', back: { en: 'music', de: 'Musik', ko: '음악', ja: '音楽' }, pronunciation: 'moo-ZEEK' },
      { id: 'gb-10', front: 'Buch', back: { en: 'book', de: 'Buch', ko: '책', ja: '本' }, pronunciation: 'bookh' },
      { id: 'gb-11', front: 'Schule', back: { en: 'school', de: 'Schule', ko: '학교', ja: '学校' }, pronunciation: 'SHOO-luh' },
      { id: 'gb-12', front: 'Arbeit', back: { en: 'work', de: 'Arbeit', ko: '일', ja: '仕事' }, pronunciation: 'AR-bait' },
      { id: 'gb-13', front: 'Glück', back: { en: 'happiness/luck', de: 'Glück', ko: '행복/행운', ja: '幸福/幸運' }, pronunciation: 'glewk' },
      { id: 'gb-14', front: 'Blume', back: { en: 'flower', de: 'Blume', ko: '꽃', ja: '花' }, pronunciation: 'BLOO-muh' },
      { id: 'gb-15', front: 'Herz', back: { en: 'heart', de: 'Herz', ko: '마음', ja: '心' }, pronunciation: 'hairts' },
      { id: 'gb-c01', noteType: 'Cloze', front: '_____, wie geht es dir?', back: { en: 'hello', de: 'Hallo', ko: '안녕하세요', ja: 'こんにちは' }, pronunciation: 'hello', extra: 'Hallo, wie geht es dir?' },
      { id: 'gb-c02', noteType: 'Cloze', front: '_____ für deine Hilfe.', back: { en: 'thank you', de: 'Danke', ko: '감사합니다', ja: 'ありがとう' }, pronunciation: 'thank you', extra: 'Danke für deine Hilfe.' },
      { id: 'gb-c03', noteType: 'Cloze', front: 'Meine _____ ist sehr groß.', back: { en: 'family', de: 'Familie', ko: '가족', ja: '家族' }, pronunciation: 'family', extra: 'Meine Familie ist sehr groß.' },
      { id: 'gb-c04', noteType: 'Cloze', front: 'Die _____ scheint heute.', back: { en: 'sun', de: 'Sonne', ko: '태양', ja: '太陽' }, pronunciation: 'sun', extra: 'Die Sonne scheint heute.' },
      { id: 'gb-c05', noteType: 'Cloze', front: 'Ich lese gerne ein _____.', back: { en: 'book', de: 'Buch', ko: '책', ja: '本' }, pronunciation: 'book', extra: 'Ich lese gerne ein Buch.' },
    ],
  },
  {
    id: 'german-travel',
    lang: 'de',
    name: 'German Travel',
    nameLocal: 'Deutsch Reisen',
    description: 'Essential German vocabulary for traveling in Germany, Austria, and Switzerland.',
    emoji: '🚂',
    accentColor: '#4338ca',
    cards: [
      { id: 'gt-01', front: 'Bahnhof', back: { en: 'train station', de: 'Bahnhof', ko: '기차역', ja: '駅' }, pronunciation: 'BAHN-hohf' },
      { id: 'gt-02', front: 'Flughafen', back: { en: 'airport', de: 'Flughafen', ko: '공항', ja: '空港' }, pronunciation: 'FLOOK-hah-fen' },
      { id: 'gt-03', front: 'Fahrkarte', back: { en: 'ticket', de: 'Fahrkarte', ko: '표', ja: '切符' }, pronunciation: 'FAHR-kar-tuh' },
      { id: 'gt-04', front: 'Reisepass', back: { en: 'passport', de: 'Reisepass', ko: '여권', ja: 'パスポート' }, pronunciation: 'RY-zuh-pahs' },
      { id: 'gt-05', front: 'Gepäck', back: { en: 'luggage', de: 'Gepäck', ko: '짐', ja: '荷物' }, pronunciation: 'guh-PEK' },
      { id: 'gt-06', front: 'Unterkunft', back: { en: 'accommodation', de: 'Unterkunft', ko: '숙소', ja: '宿泊施設' }, pronunciation: 'OON-ter-koonft' },
      { id: 'gt-07', front: 'Stadtplan', back: { en: 'city map', de: 'Stadtplan', ko: '시내 지도', ja: '市内地図' }, pronunciation: 'SHTAHT-plahn' },
      { id: 'gt-08', front: 'Ausgang', back: { en: 'exit', de: 'Ausgang', ko: '출구', ja: '出口' }, pronunciation: 'OWS-gahng' },
      { id: 'gt-09', front: 'Eingang', back: { en: 'entrance', de: 'Eingang', ko: '입구', ja: '入口' }, pronunciation: 'AIN-gahng' },
      { id: 'gt-10', front: 'Museum', back: { en: 'museum', de: 'Museum', ko: '박물관', ja: '美術館' }, pronunciation: 'moo-ZAY-oom' },
      { id: 'gt-11', front: 'Apotheke', back: { en: 'pharmacy', de: 'Apotheke', ko: '약국', ja: '薬局' }, pronunciation: 'ah-poh-TAY-kuh' },
      { id: 'gt-12', front: 'Geld', back: { en: 'money', de: 'Geld', ko: '돈', ja: 'お金' }, pronunciation: 'gelt' },
      { id: 'gt-13', front: 'Schloss', back: { en: 'castle', de: 'Schloss', ko: '성', ja: '城' }, pronunciation: 'shloss' },
      { id: 'gt-14', front: 'Biergarten', back: { en: 'beer garden', de: 'Biergarten', ko: '비어가든', ja: 'ビアガーデン' }, pronunciation: 'BEER-gar-ten' },
      { id: 'gt-15', front: 'Andenken', back: { en: 'souvenir', de: 'Andenken', ko: '기념품', ja: 'お土産' }, pronunciation: 'AHN-den-ken' },
      { id: 'gt-c01', noteType: 'Cloze', front: 'Wo ist der _____?', back: { en: 'train station', de: 'Bahnhof', ko: '기차역', ja: '駅' }, pronunciation: 'train station', extra: 'Wo ist der Bahnhof?' },
      { id: 'gt-c02', noteType: 'Cloze', front: 'Ich brauche eine _____.', back: { en: 'ticket', de: 'Fahrkarte', ko: '표', ja: '切符' }, pronunciation: 'ticket', extra: 'Ich brauche eine Fahrkarte.' },
      { id: 'gt-c03', noteType: 'Cloze', front: 'Vergiss deinen _____ nicht.', back: { en: 'passport', de: 'Reisepass', ko: '여권', ja: 'パスポート' }, pronunciation: 'passport', extra: 'Vergiss deinen Reisepass nicht.' },
      { id: 'gt-c04', noteType: 'Cloze', front: 'Wir besuchen das _____ Neuschwanstein.', back: { en: 'castle', de: 'Schloss', ko: '성', ja: '城' }, pronunciation: 'castle', extra: 'Wir besuchen das Schloss Neuschwanstein.' },
      { id: 'gt-c05', noteType: 'Cloze', front: 'Lass uns im _____ essen.', back: { en: 'beer garden', de: 'Biergarten', ko: '비어가든', ja: 'ビアガーデン' }, pronunciation: 'beer garden', extra: 'Lass uns im Biergarten essen.' },
    ],
  },
];
