export interface LocalizedText { en: string; ko: string; ja: string }

export interface DemoCard {
  id: string;
  front: string;        // Basic: target word / Cloze: sentence with _____
  back: LocalizedText;   // Basic: meaning / Cloze: answer word (localized)
  pronunciation: string; // romanization (shown in accent color)
  noteType?: 'Basic' | 'Cloze';
  extra?: string;       // Cloze: full sentence
}

export type DemoLang = 'ko' | 'ja' | 'en';

export interface DemoDeck {
  id: string;
  lang: DemoLang;
  name: string;
  nameLocal: string;    // native language name (한국어 기초, 日本語 基礎, etc.)
  description: string;
  emoji: string;
  accentColor: string;
  cards: DemoCard[];
}

export const DEMO_DECKS: DemoDeck[] = [
  {
    id: 'korean-basics',
    lang: 'ko',
    name: 'Korean Basics',
    nameLocal: '한국어 기초',
    description: 'Essential everyday Korean vocabulary — perfect for beginners.',
    emoji: '🇰🇷',
    accentColor: '#3730a3',
    cards: [
      { id: 'kb-01', front: '사랑', back: { en: 'love', ko: '사랑', ja: '愛' }, pronunciation: 'sarang' },
      { id: 'kb-02', front: '행복', back: { en: 'happiness', ko: '행복', ja: '幸せ' }, pronunciation: 'haengbok' },
      { id: 'kb-03', front: '친구', back: { en: 'friend', ko: '친구', ja: '友達' }, pronunciation: 'chingu' },
      { id: 'kb-04', front: '가족', back: { en: 'family', ko: '가족', ja: '家族' }, pronunciation: 'gajok' },
      { id: 'kb-05', front: '집', back: { en: 'home', ko: '집', ja: '家' }, pronunciation: 'jip' },
      { id: 'kb-06', front: '음식', back: { en: 'food', ko: '음식', ja: '食べ物' }, pronunciation: 'eumsik' },
      { id: 'kb-07', front: '음악', back: { en: 'music', ko: '음악', ja: '音楽' }, pronunciation: 'eumak' },
      { id: 'kb-08', front: '하늘', back: { en: 'sky', ko: '하늘', ja: '空' }, pronunciation: 'haneul' },
      { id: 'kb-09', front: '꿈', back: { en: 'dream', ko: '꿈', ja: '夢' }, pronunciation: 'kkum' },
      { id: 'kb-10', front: '시간', back: { en: 'time', ko: '시간', ja: '時間' }, pronunciation: 'sigan' },
      { id: 'kb-11', front: '학교', back: { en: 'school', ko: '학교', ja: '学校' }, pronunciation: 'hakgyo' },
      { id: 'kb-12', front: '물', back: { en: 'water', ko: '물', ja: '水' }, pronunciation: 'mul' },
      { id: 'kb-13', front: '빛', back: { en: 'light', ko: '빛', ja: '光' }, pronunciation: 'bit' },
      { id: 'kb-14', front: '책', back: { en: 'book', ko: '책', ja: '本' }, pronunciation: 'chaek' },
      { id: 'kb-15', front: '고양이', back: { en: 'cat', ko: '고양이', ja: '猫' }, pronunciation: 'goyangi' },
      // Cloze cards
      { id: 'kb-c01', noteType: 'Cloze', front: '나는 가족을 _____합니다.', back: { en: 'love', ko: '사랑', ja: '愛' }, pronunciation: 'love', extra: '나는 가족을 사랑합니다.' },
      { id: 'kb-c02', noteType: 'Cloze', front: '함께 있으면 _____해요.', back: { en: 'happiness', ko: '행복', ja: '幸せ' }, pronunciation: 'happiness', extra: '함께 있으면 행복해요.' },
      { id: 'kb-c03', noteType: 'Cloze', front: '_____에서 열심히 공부해요.', back: { en: 'school', ko: '학교', ja: '学校' }, pronunciation: 'school', extra: '학교에서 열심히 공부해요.' },
      { id: 'kb-c04', noteType: 'Cloze', front: '좋은 _____을 들으면 기분이 좋아요.', back: { en: 'music', ko: '음악', ja: '音楽' }, pronunciation: 'music', extra: '좋은 음악을 들으면 기분이 좋아요.' },
      { id: 'kb-c05', noteType: 'Cloze', front: '파란 _____을 바라보며 꿈을 꿔요.', back: { en: 'sky', ko: '하늘', ja: '空' }, pronunciation: 'sky', extra: '파란 하늘을 바라보며 꿈을 꿔요.' },
    ],
  },
  {
    id: 'kdrama',
    lang: 'ko',
    name: 'K-Drama Essentials',
    nameLocal: '드라마 필수 단어',
    description: 'Words from Squid Game, Crash Landing on You, and more hit dramas.',
    emoji: '🎬',
    accentColor: '#831843',
    cards: [
      { id: 'kd-01', front: '운명', back: { en: 'fate', ko: '운명', ja: '運命' }, pronunciation: 'unmyeong' },
      { id: 'kd-02', front: '기억', back: { en: 'memory', ko: '기억', ja: '記憶' }, pronunciation: 'gieok' },
      { id: 'kd-03', front: '비밀', back: { en: 'secret', ko: '비밀', ja: '秘密' }, pronunciation: 'bimil' },
      { id: 'kd-04', front: '용기', back: { en: 'courage', ko: '용기', ja: '勇気' }, pronunciation: 'yonggi' },
      { id: 'kd-05', front: '희망', back: { en: 'hope', ko: '희망', ja: '希望' }, pronunciation: 'huimang' },
      { id: 'kd-06', front: '눈물', back: { en: 'tears', ko: '눈물', ja: '涙' }, pronunciation: 'nunmul' },
      { id: 'kd-07', front: '선택', back: { en: 'choice', ko: '선택', ja: '選択' }, pronunciation: 'seonteok' },
      { id: 'kd-08', front: '게임', back: { en: 'game', ko: '게임', ja: 'ゲーム' }, pronunciation: 'geim' },
      { id: 'kd-09', front: '진실', back: { en: 'truth', ko: '진실', ja: '真実' }, pronunciation: 'jinsil' },
      { id: 'kd-10', front: '배신', back: { en: 'betrayal', ko: '배신', ja: '裏切り' }, pronunciation: 'baesin' },
      { id: 'kd-11', front: '복수', back: { en: 'revenge', ko: '복수', ja: '復讐' }, pronunciation: 'boksu' },
      { id: 'kd-12', front: '기회', back: { en: 'opportunity', ko: '기회', ja: '機会' }, pronunciation: 'gihoe' },
      { id: 'kd-13', front: '그리움', back: { en: 'longing', ko: '그리움', ja: '恋しさ' }, pronunciation: 'geuriwum' },
      { id: 'kd-14', front: '마음', back: { en: 'heart', ko: '마음', ja: '心' }, pronunciation: 'maeum' },
      { id: 'kd-15', front: '상금', back: { en: 'prize money', ko: '상금', ja: '賞金' }, pronunciation: 'sanggeum' },
      // Cloze cards
      { id: 'kd-c01', noteType: 'Cloze', front: '우리가 만난 건 _____이었어요.', back: { en: 'destiny', ko: '운명', ja: '運命' }, pronunciation: 'destiny', extra: '우리가 만난 건 운명이었어요.' },
      { id: 'kd-c02', noteType: 'Cloze', front: '아직 _____을 잃지 마세요.', back: { en: 'hope', ko: '희망', ja: '希望' }, pronunciation: 'hope', extra: '아직 희망을 잃지 마세요.' },
      { id: 'kd-c03', noteType: 'Cloze', front: '그녀의 눈에 _____이 흘렀어요.', back: { en: 'tears', ko: '눈물', ja: '涙' }, pronunciation: 'tears', extra: '그녀의 눈에 눈물이 흘렀어요.' },
      { id: 'kd-c04', noteType: 'Cloze', front: '당신의 _____을 믿어요.', back: { en: 'heart', ko: '마음', ja: '心' }, pronunciation: 'heart', extra: '당신의 마음을 믿어요.' },
      { id: 'kd-c05', noteType: 'Cloze', front: '모든 것에는 나만의 _____가 있어요.', back: { en: 'secret', ko: '비밀', ja: '秘密' }, pronunciation: 'secret', extra: '모든 것에는 나만의 비밀이 있어요.' },
    ],
  },
  {
    id: 'kpop',
    lang: 'ko',
    name: 'K-Pop Vocabulary',
    nameLocal: 'K-팝 단어',
    description: 'Words from BTS, BLACKPINK, TWICE and more iconic songs.',
    emoji: '🎤',
    accentColor: '#065f46',
    cards: [
      { id: 'kp-01', front: '우주', back: { en: 'universe', ko: '우주', ja: '宇宙' }, pronunciation: 'uju' },
      { id: 'kp-02', front: '별', back: { en: 'star', ko: '별', ja: '星' }, pronunciation: 'byeol' },
      { id: 'kp-03', front: '영원', back: { en: 'eternity', ko: '영원', ja: '永遠' }, pronunciation: 'yeongwon' },
      { id: 'kp-04', front: '노래', back: { en: 'song', ko: '노래', ja: '歌' }, pronunciation: 'norae' },
      { id: 'kp-05', front: '춤', back: { en: 'dance', ko: '춤', ja: 'ダンス' }, pronunciation: 'chum' },
      { id: 'kp-06', front: '자유', back: { en: 'freedom', ko: '자유', ja: '自由' }, pronunciation: 'jayu' },
      { id: 'kp-07', front: '설레임', back: { en: 'flutter', ko: '설레임', ja: 'ときめき' }, pronunciation: 'seolleim' },
      { id: 'kp-08', front: '함께', back: { en: 'together', ko: '함께', ja: '一緒に' }, pronunciation: 'hamkke' },
      { id: 'kp-09', front: '소리', back: { en: 'sound', ko: '소리', ja: '音' }, pronunciation: 'sori' },
      { id: 'kp-10', front: '태양', back: { en: 'sun', ko: '태양', ja: '太陽' }, pronunciation: 'taeyang' },
      { id: 'kp-11', front: '파도', back: { en: 'wave', ko: '파도', ja: '波' }, pronunciation: 'pado' },
      { id: 'kp-12', front: '이야기', back: { en: 'story', ko: '이야기', ja: '物語' }, pronunciation: 'iyagi' },
      { id: 'kp-13', front: '행운', back: { en: 'good luck', ko: '행운', ja: '幸運' }, pronunciation: 'haengun' },
      { id: 'kp-14', front: '반짝', back: { en: 'sparkle', ko: '반짝', ja: 'きらめき' }, pronunciation: 'banjjak' },
      { id: 'kp-15', front: '세상', back: { en: 'world', ko: '세상', ja: '世界' }, pronunciation: 'sesang' },
      // Cloze cards
      { id: 'kp-c01', noteType: 'Cloze', front: '저 _____처럼 빛나고 싶어.', back: { en: 'star', ko: '별', ja: '星' }, pronunciation: 'star', extra: '저 별처럼 빛나고 싶어.' },
      { id: 'kp-c02', noteType: 'Cloze', front: '우리 _____히 같이 있자.', back: { en: 'forever', ko: '영원', ja: '永遠' }, pronunciation: 'forever', extra: '우리 영원히 같이 있자.' },
      { id: 'kp-c03', noteType: 'Cloze', front: '온 _____이 우리 편이야.', back: { en: 'world', ko: '세상', ja: '世界' }, pronunciation: 'world', extra: '온 세상이 우리 편이야.' },
      { id: 'kp-c04', noteType: 'Cloze', front: '네 _____가 나를 설레게 해.', back: { en: 'song', ko: '노래', ja: '歌' }, pronunciation: 'song', extra: '네 노래가 나를 설레게 해.' },
      { id: 'kp-c05', noteType: 'Cloze', front: '네가 있는 곳이 내 _____야.', back: { en: 'universe', ko: '우주', ja: '宇宙' }, pronunciation: 'universe', extra: '네가 있는 곳이 내 우주야.' },
    ],
  },
  {
    id: 'kpop-fandom',
    lang: 'ko',
    name: 'K-Pop Fandom Terms',
    nameLocal: 'K-팝 팬덤 용어',
    description: 'Essential fandom terms every K-pop fan should know — 컴백, 팬싸, 응원봉 and more.',
    emoji: '💜',
    accentColor: '#7c3aed',
    cards: [
      { id: 'kf-01', front: '컴백', back: { en: 'comeback', ko: '컴백', ja: 'カムバック' }, pronunciation: 'keombaek' },
      { id: 'kf-02', front: '팬싸', back: { en: 'fan signing event', ko: '팬싸인회', ja: 'サイン会' }, pronunciation: 'paenssa' },
      { id: 'kf-03', front: '응원봉', back: { en: 'lightstick', ko: '응원봉', ja: 'ペンライト' }, pronunciation: 'eungwonbong' },
      { id: 'kf-04', front: '덕질', back: { en: 'fangirling/fanboying', ko: '덕질', ja: 'オタ活' }, pronunciation: 'deokjil' },
      { id: 'kf-05', front: '최애', back: { en: 'ultimate bias', ko: '최애', ja: '推し' }, pronunciation: 'choeae' },
      { id: 'kf-06', front: '무대', back: { en: 'stage', ko: '무대', ja: 'ステージ' }, pronunciation: 'mudae' },
      { id: 'kf-07', front: '안무', back: { en: 'choreography', ko: '안무', ja: '振り付け' }, pronunciation: 'anmu' },
      { id: 'kf-08', front: '음원', back: { en: 'digital release', ko: '음원', ja: '音源' }, pronunciation: 'eumwon' },
      { id: 'kf-09', front: '총공', back: { en: 'mass streaming', ko: '총공', ja: '総攻撃' }, pronunciation: 'chonggong' },
      { id: 'kf-10', front: '직캠', back: { en: 'fancam', ko: '직캠', ja: 'ファンカム' }, pronunciation: 'jikcam' },
      { id: 'kf-11', front: '떡밥', back: { en: 'teaser/hint', ko: '떡밥', ja: 'ティーザー' }, pronunciation: 'tteokbap' },
      { id: 'kf-12', front: '입덕', back: { en: 'becoming a fan', ko: '입덕', ja: '推し始め' }, pronunciation: 'ipdeok' },
      { id: 'kf-13', front: '탈덕', back: { en: 'leaving fandom', ko: '탈덕', ja: '推し卒' }, pronunciation: 'taldeok' },
      { id: 'kf-14', front: '멤버', back: { en: 'member', ko: '멤버', ja: 'メンバー' }, pronunciation: 'membeo' },
      { id: 'kf-15', front: '공연', back: { en: 'concert/performance', ko: '공연', ja: 'コンサート' }, pronunciation: 'gongyeon' },
      // Cloze cards
      { id: 'kf-c01', noteType: 'Cloze', front: '오늘 _____에서 최애를 만났어요!', back: { en: 'fan signing event', ko: '팬싸인회', ja: 'サイン会' }, pronunciation: 'fan signing event', extra: '오늘 팬싸에서 최애를 만났어요!' },
      { id: 'kf-c02', noteType: 'Cloze', front: '새 앨범 _____이 드디어 발표됐어요.', back: { en: 'comeback', ko: '컴백', ja: 'カムバック' }, pronunciation: 'comeback', extra: '새 앨범 컴백이 드디어 발표됐어요.' },
      { id: 'kf-c03', noteType: 'Cloze', front: '_____을 흔들며 함께 노래했어요.', back: { en: 'lightstick', ko: '응원봉', ja: 'ペンライト' }, pronunciation: 'lightstick', extra: '응원봉을 흔들며 함께 노래했어요.' },
      { id: 'kf-c04', noteType: 'Cloze', front: '이 _____는 정말 대단해요!', back: { en: 'choreography', ko: '안무', ja: '振り付け' }, pronunciation: 'choreography', extra: '이 안무는 정말 대단해요!' },
      { id: 'kf-c05', noteType: 'Cloze', front: '내 _____는 이 그룹의 리더예요.', back: { en: 'favorite member', ko: '최애', ja: '推し' }, pronunciation: 'favorite member', extra: '내 최애는 이 그룹의 리더예요.' },
    ],
  },
  {
    id: 'kpop-emotions',
    lang: 'ko',
    name: 'K-Pop Emotion Words',
    nameLocal: 'K-팝 감성 단어',
    description: 'Deep emotional vocabulary found in K-pop ballads and love songs.',
    emoji: '🌙',
    accentColor: '#be185d',
    cards: [
      { id: 'ke-01', front: '그리움', back: { en: 'longing/yearning', ko: '그리움', ja: '恋しさ' }, pronunciation: 'geuriwum' },
      { id: 'ke-02', front: '설렘', back: { en: 'excitement/flutter', ko: '설렘', ja: 'ときめき' }, pronunciation: 'seollem' },
      { id: 'ke-03', front: '이별', back: { en: 'farewell/breakup', ko: '이별', ja: '別れ' }, pronunciation: 'ibyeol' },
      { id: 'ke-04', front: '추억', back: { en: 'memories', ko: '추억', ja: '思い出' }, pronunciation: 'chueok' },
      { id: 'ke-05', front: '눈물', back: { en: 'tears', ko: '눈물', ja: '涙' }, pronunciation: 'nunmul' },
      { id: 'ke-06', front: '약속', back: { en: 'promise', ko: '약속', ja: '約束' }, pronunciation: 'yaksok' },
      { id: 'ke-07', front: '고백', back: { en: 'confession', ko: '고백', ja: '告白' }, pronunciation: 'gobaek' },
      { id: 'ke-08', front: '위로', back: { en: 'comfort', ko: '위로', ja: '慰め' }, pronunciation: 'wiro' },
      { id: 'ke-09', front: '기다림', back: { en: 'waiting', ko: '기다림', ja: '待つこと' }, pronunciation: 'gidarim' },
      { id: 'ke-10', front: '외로움', back: { en: 'loneliness', ko: '외로움', ja: '寂しさ' }, pronunciation: 'oeroum' },
      { id: 'ke-11', front: '떨림', back: { en: 'trembling', ko: '떨림', ja: '震え' }, pronunciation: 'tteollim' },
      { id: 'ke-12', front: '바램', back: { en: 'wish/hope', ko: '바램', ja: '願い' }, pronunciation: 'baraem' },
      { id: 'ke-13', front: '미련', back: { en: 'lingering attachment', ko: '미련', ja: '未練' }, pronunciation: 'miryeon' },
      { id: 'ke-14', front: '아픔', back: { en: 'pain/heartache', ko: '아픔', ja: '痛み' }, pronunciation: 'apeum' },
      { id: 'ke-15', front: '봄날', back: { en: 'spring day', ko: '봄날', ja: '春の日' }, pronunciation: 'bomnal' },
      // Cloze cards
      { id: 'ke-c01', noteType: 'Cloze', front: '너를 향한 _____이 멈추지 않아.', back: { en: 'longing', ko: '그리움', ja: '恋しさ' }, pronunciation: 'longing', extra: '너를 향한 그리움이 멈추지 않아.' },
      { id: 'ke-c02', noteType: 'Cloze', front: '이 _____을 영원히 간직할게.', back: { en: 'memory', ko: '추억', ja: '思い出' }, pronunciation: 'memory', extra: '이 추억을 영원히 간직할게.' },
      { id: 'ke-c03', noteType: 'Cloze', front: '너에게 _____을 하고 싶어.', back: { en: 'confession', ko: '고백', ja: '告白' }, pronunciation: 'confession', extra: '너에게 고백을 하고 싶어.' },
      { id: 'ke-c04', noteType: 'Cloze', front: '긴 _____의 끝에 네가 왔어.', back: { en: 'waiting', ko: '기다림', ja: '待つこと' }, pronunciation: 'waiting', extra: '긴 기다림의 끝에 네가 왔어.' },
      { id: 'ke-c05', noteType: 'Cloze', front: '_____이 지나면 다시 만날 거야.', back: { en: 'spring day', ko: '봄날', ja: '春の日' }, pronunciation: 'spring day', extra: '봄날이 지나면 다시 만날 거야.' },
    ],
  },
  {
    id: 'japanese-basics',
    lang: 'ja',
    name: 'Japanese Basics',
    nameLocal: '日本語 基礎',
    description: 'Essential everyday Japanese vocabulary — perfect for beginners.',
    emoji: '🇯🇵',
    accentColor: '#dc2626',
    cards: [
      { id: 'jb-01', front: '愛', back: { en: 'love', ko: '사랑', ja: '愛' }, pronunciation: 'ai' },
      { id: 'jb-02', front: '友達', back: { en: 'friend', ko: '친구', ja: '友達' }, pronunciation: 'tomodachi' },
      { id: 'jb-03', front: '家族', back: { en: 'family', ko: '가족', ja: '家族' }, pronunciation: 'kazoku' },
      { id: 'jb-04', front: '学校', back: { en: 'school', ko: '학교', ja: '学校' }, pronunciation: 'gakkou' },
      { id: 'jb-05', front: '食べ物', back: { en: 'food', ko: '음식', ja: '食べ物' }, pronunciation: 'tabemono' },
      { id: 'jb-06', front: '音楽', back: { en: 'music', ko: '음악', ja: '音楽' }, pronunciation: 'ongaku' },
      { id: 'jb-07', front: '空', back: { en: 'sky', ko: '하늘', ja: '空' }, pronunciation: 'sora' },
      { id: 'jb-08', front: '夢', back: { en: 'dream', ko: '꿈', ja: '夢' }, pronunciation: 'yume' },
      { id: 'jb-09', front: '時間', back: { en: 'time', ko: '시간', ja: '時間' }, pronunciation: 'jikan' },
      { id: 'jb-10', front: '水', back: { en: 'water', ko: '물', ja: '水' }, pronunciation: 'mizu' },
      { id: 'jb-11', front: '光', back: { en: 'light', ko: '빛', ja: '光' }, pronunciation: 'hikari' },
      { id: 'jb-12', front: '本', back: { en: 'book', ko: '책', ja: '本' }, pronunciation: 'hon' },
      { id: 'jb-13', front: '猫', back: { en: 'cat', ko: '고양이', ja: '猫' }, pronunciation: 'neko' },
      { id: 'jb-14', front: '花', back: { en: 'flower', ko: '꽃', ja: '花' }, pronunciation: 'hana' },
      { id: 'jb-15', front: '心', back: { en: 'heart', ko: '마음', ja: '心' }, pronunciation: 'kokoro' },
      // Cloze cards
      { id: 'jb-c01', noteType: 'Cloze', front: '毎日_____を飲みます。', back: { en: 'water', ko: '물', ja: '水' }, pronunciation: 'water', extra: '毎日水を飲みます。' },
      { id: 'jb-c02', noteType: 'Cloze', front: '_____が青くて綺麗です。', back: { en: 'sky', ko: '하늘', ja: '空' }, pronunciation: 'sky', extra: '空が青くて綺麗です。' },
      { id: 'jb-c03', noteType: 'Cloze', front: '好きな_____は寿司です。', back: { en: 'food', ko: '음식', ja: '食べ物' }, pronunciation: 'food', extra: '好きな食べ物は寿司です。' },
      { id: 'jb-c04', noteType: 'Cloze', front: '毎朝_____を聴きます。', back: { en: 'music', ko: '음악', ja: '音楽' }, pronunciation: 'music', extra: '毎朝音楽を聴きます。' },
      { id: 'jb-c05', noteType: 'Cloze', front: '彼女の_____はとても優しい。', back: { en: 'heart', ko: '마음', ja: '心' }, pronunciation: 'heart', extra: '彼女の心はとても優しい。' },
    ],
  },
  {
    id: 'anime',
    lang: 'ja',
    name: 'Anime Essentials',
    nameLocal: 'アニメ必須単語',
    description: 'Words from Naruto, One Piece, Demon Slayer and more hit anime.',
    emoji: '⛩️',
    accentColor: '#7c3aed',
    cards: [
      { id: 'an-01', front: '仲間', back: { en: 'companion', ko: '동료', ja: '仲間' }, pronunciation: 'nakama' },
      { id: 'an-02', front: '約束', back: { en: 'promise', ko: '약속', ja: '約束' }, pronunciation: 'yakusoku' },
      { id: 'an-03', front: '勇気', back: { en: 'courage', ko: '용기', ja: '勇気' }, pronunciation: 'yuuki' },
      { id: 'an-04', front: '戦い', back: { en: 'battle', ko: '전투', ja: '戦い' }, pronunciation: 'tatakai' },
      { id: 'an-05', front: '希望', back: { en: 'hope', ko: '희망', ja: '希望' }, pronunciation: 'kibou' },
      { id: 'an-06', front: '力', back: { en: 'power', ko: '힘', ja: '力' }, pronunciation: 'chikara' },
      { id: 'an-07', front: '運命', back: { en: 'destiny', ko: '운명', ja: '運命' }, pronunciation: 'unmei' },
      { id: 'an-08', front: '守る', back: { en: 'protect', ko: '지키다', ja: '守る' }, pronunciation: 'mamoru' },
      { id: 'an-09', front: '魔法', back: { en: 'magic', ko: '마법', ja: '魔法' }, pronunciation: 'mahou' },
      { id: 'an-10', front: '冒険', back: { en: 'adventure', ko: '모험', ja: '冒険' }, pronunciation: 'bouken' },
      { id: 'an-11', front: '正義', back: { en: 'justice', ko: '정의', ja: '正義' }, pronunciation: 'seigi' },
      { id: 'an-12', front: '絆', back: { en: 'bond', ko: '유대', ja: '絆' }, pronunciation: 'kizuna' },
      { id: 'an-13', front: '覚悟', back: { en: 'resolve', ko: '각오', ja: '覚悟' }, pronunciation: 'kakugo' },
      { id: 'an-14', front: '修行', back: { en: 'training', ko: '수련', ja: '修行' }, pronunciation: 'shugyou' },
      { id: 'an-15', front: '英雄', back: { en: 'hero', ko: '영웅', ja: '英雄' }, pronunciation: 'eiyuu' },
      // Cloze cards
      { id: 'an-c01', noteType: 'Cloze', front: '友達との_____は必ず守る。', back: { en: 'promise', ko: '약속', ja: '約束' }, pronunciation: 'promise', extra: '友達との約束は必ず守る。' },
      { id: 'an-c02', noteType: 'Cloze', front: '君を_____ために戦い続ける。', back: { en: 'to protect', ko: '지키다', ja: '守る' }, pronunciation: 'to protect', extra: '君を守るために戦い続ける。' },
      { id: 'an-c03', noteType: 'Cloze', front: 'これが僕たちの_____だ。', back: { en: 'fate', ko: '운명', ja: '運命' }, pronunciation: 'fate', extra: 'これが僕たちの運命だ。' },
      { id: 'an-c04', noteType: 'Cloze', front: '_____の力で世界を救う。', back: { en: 'magic', ko: '마법', ja: '魔法' }, pronunciation: 'magic', extra: '魔法の力で世界を救う。' },
      { id: 'an-c05', noteType: 'Cloze', front: '諦めない_____がある限り。', back: { en: 'courage', ko: '용기', ja: '勇気' }, pronunciation: 'courage', extra: '諦めない勇気がある限り。' },
    ],
  },
  {
    id: 'jpop',
    lang: 'ja',
    name: 'J-Pop Vocabulary',
    nameLocal: 'J-ポップ単語',
    description: 'Words from YOASOBI, Ado, Kenshi Yonezu and more iconic songs.',
    emoji: '🎵',
    accentColor: '#0891b2',
    cards: [
      { id: 'jp-01', front: '桜', back: { en: 'cherry blossom', ko: '벚꽃', ja: '桜' }, pronunciation: 'sakura' },
      { id: 'jp-02', front: '永遠', back: { en: 'eternity', ko: '영원', ja: '永遠' }, pronunciation: 'eien' },
      { id: 'jp-03', front: '涙', back: { en: 'tears', ko: '눈물', ja: '涙' }, pronunciation: 'namida' },
      { id: 'jp-04', front: '世界', back: { en: 'world', ko: '세계', ja: '世界' }, pronunciation: 'sekai' },
      { id: 'jp-05', front: '星', back: { en: 'star', ko: '별', ja: '星' }, pronunciation: 'hoshi' },
      { id: 'jp-06', front: '歌', back: { en: 'song', ko: '노래', ja: '歌' }, pronunciation: 'uta' },
      { id: 'jp-07', front: '風', back: { en: 'wind', ko: '바람', ja: '風' }, pronunciation: 'kaze' },
      { id: 'jp-08', front: '恋', back: { en: 'romance', ko: '사랑', ja: '恋' }, pronunciation: 'koi' },
      { id: 'jp-09', front: '明日', back: { en: 'tomorrow', ko: '내일', ja: '明日' }, pronunciation: 'ashita' },
      { id: 'jp-10', front: '輝き', back: { en: 'radiance', ko: '빛남', ja: '輝き' }, pronunciation: 'kagayaki' },
      { id: 'jp-11', front: '願い', back: { en: 'wish', ko: '소원', ja: '願い' }, pronunciation: 'negai' },
      { id: 'jp-12', front: '声', back: { en: 'voice', ko: '목소리', ja: '声' }, pronunciation: 'koe' },
      { id: 'jp-13', front: '旅', back: { en: 'journey', ko: '여행', ja: '旅' }, pronunciation: 'tabi' },
      { id: 'jp-14', front: '未来', back: { en: 'future', ko: '미래', ja: '未来' }, pronunciation: 'mirai' },
      { id: 'jp-15', front: '海', back: { en: 'sea', ko: '바다', ja: '海' }, pronunciation: 'umi' },
      // Cloze cards
      { id: 'jp-c01', noteType: 'Cloze', front: 'あなたの_____が聴こえる。', back: { en: 'voice', ko: '목소리', ja: '声' }, pronunciation: 'voice', extra: 'あなたの声が聴こえる。' },
      { id: 'jp-c02', noteType: 'Cloze', front: '春には_____が咲く。', back: { en: 'cherry blossom', ko: '벚꽃', ja: '桜' }, pronunciation: 'cherry blossom', extra: '春には桜が咲く。' },
      { id: 'jp-c03', noteType: 'Cloze', front: '瞳に_____が光る。', back: { en: 'tears', ko: '눈물', ja: '涙' }, pronunciation: 'tears', extra: '瞳に涙が光る。' },
      { id: 'jp-c04', noteType: 'Cloze', front: '君と_____に旅したい。', back: { en: 'eternity', ko: '영원', ja: '永遠' }, pronunciation: 'eternity', extra: '君と永遠に旅したい。' },
      { id: 'jp-c05', noteType: 'Cloze', front: '君への_____は届くだろう。', back: { en: 'wish', ko: '소원', ja: '願い' }, pronunciation: 'wish', extra: '君への願いは届くだろう。' },
    ],
  },
  // ─── English Decks ────────────────────────────────────────────────
  {
    id: 'english-basics',
    lang: 'en',
    name: 'English Basics',
    nameLocal: 'English Basics',
    description: 'Essential English vocabulary for everyday communication.',
    emoji: '🇺🇸',
    accentColor: '#2563eb',
    cards: [
      { id: 'eb-01', front: 'appreciate', back: { en: 'to value highly', ko: '감사하다', ja: '感謝する' }, pronunciation: 'uh-PREE-shee-ayt' },
      { id: 'eb-02', front: 'opportunity', back: { en: 'a favorable chance', ko: '기회', ja: '機会' }, pronunciation: 'op-er-TOO-nuh-tee' },
      { id: 'eb-03', front: 'experience', back: { en: 'practical knowledge', ko: '경험', ja: '経験' }, pronunciation: 'ik-SPEER-ee-uhns' },
      { id: 'eb-04', front: 'challenge', back: { en: 'a difficult task', ko: '도전', ja: '挑戦' }, pronunciation: 'CHAL-inj' },
      { id: 'eb-05', front: 'confidence', back: { en: 'belief in oneself', ko: '자신감', ja: '自信' }, pronunciation: 'KON-fih-duhns' },
      { id: 'eb-06', front: 'determine', back: { en: 'to decide firmly', ko: '결정하다', ja: '決定する' }, pronunciation: 'dih-TUR-min' },
      { id: 'eb-07', front: 'environment', back: { en: 'surroundings', ko: '환경', ja: '環境' }, pronunciation: 'en-VY-ruhn-muhnt' },
      { id: 'eb-08', front: 'knowledge', back: { en: 'information learned', ko: '지식', ja: '知識' }, pronunciation: 'NOL-ij' },
      { id: 'eb-09', front: 'responsibility', back: { en: 'a duty to deal with', ko: '책임', ja: '責任' }, pronunciation: 'rih-spon-suh-BIL-uh-tee' },
      { id: 'eb-10', front: 'communicate', back: { en: 'to share information', ko: '소통하다', ja: '伝える' }, pronunciation: 'kuh-MYOO-nih-kayt' },
      { id: 'eb-11', front: 'accomplish', back: { en: 'to achieve', ko: '달성하다', ja: '達成する' }, pronunciation: 'uh-KOM-plish' },
      { id: 'eb-12', front: 'encourage', back: { en: 'to give support', ko: '격려하다', ja: '励ます' }, pronunciation: 'en-KUR-ij' },
      { id: 'eb-13', front: 'perspective', back: { en: 'a point of view', ko: '관점', ja: '視点' }, pronunciation: 'per-SPEK-tiv' },
      { id: 'eb-14', front: 'independent', back: { en: 'self-reliant', ko: '독립적인', ja: '独立した' }, pronunciation: 'in-duh-PEN-duhnt' },
      { id: 'eb-15', front: 'volunteer', back: { en: 'to offer help freely', ko: '자원봉사하다', ja: 'ボランティアする' }, pronunciation: 'vol-uhn-TEER' },
      // Cloze cards
      { id: 'eb-c01', noteType: 'Cloze', front: 'I really _____ your help.', back: { en: 'appreciate', ko: '감사하다', ja: '感謝する' }, pronunciation: 'uh-PREE-shee-ayt', extra: 'I really appreciate your help.' },
      { id: 'eb-c02', noteType: 'Cloze', front: 'This is a great _____ to learn.', back: { en: 'opportunity', ko: '기회', ja: '機会' }, pronunciation: 'op-er-TOO-nuh-tee', extra: 'This is a great opportunity to learn.' },
      { id: 'eb-c03', noteType: 'Cloze', front: 'She has a lot of _____ in herself.', back: { en: 'confidence', ko: '자신감', ja: '自信' }, pronunciation: 'KON-fih-duhns', extra: 'She has a lot of confidence in herself.' },
      { id: 'eb-c04', noteType: 'Cloze', front: 'We need to _____ more effectively.', back: { en: 'communicate', ko: '소통하다', ja: '伝える' }, pronunciation: 'kuh-MYOO-nih-kayt', extra: 'We need to communicate more effectively.' },
      { id: 'eb-c05', noteType: 'Cloze', front: 'It is your _____ to finish this.', back: { en: 'responsibility', ko: '책임', ja: '責任' }, pronunciation: 'rih-spon-suh-BIL-uh-tee', extra: 'It is your responsibility to finish this.' },
    ],
  },
  {
    id: 'travel-english',
    lang: 'en',
    name: 'Travel English',
    nameLocal: 'Travel English',
    description: 'Essential English vocabulary for traveling abroad.',
    emoji: '✈️',
    accentColor: '#059669',
    cards: [
      { id: 'et-01', front: 'reservation', back: { en: 'a booking', ko: '예약', ja: '予約' }, pronunciation: 'rez-er-VAY-shuhn' },
      { id: 'et-02', front: 'departure', back: { en: 'the act of leaving', ko: '출발', ja: '出発' }, pronunciation: 'dih-PAR-chur' },
      { id: 'et-03', front: 'accommodation', back: { en: 'a place to stay', ko: '숙소', ja: '宿泊施設' }, pronunciation: 'uh-kom-uh-DAY-shuhn' },
      { id: 'et-04', front: 'destination', back: { en: 'a place to go', ko: '목적지', ja: '目的地' }, pronunciation: 'des-tuh-NAY-shuhn' },
      { id: 'et-05', front: 'itinerary', back: { en: 'a travel plan', ko: '여행일정', ja: '旅程' }, pronunciation: 'eye-TIN-uh-rer-ee' },
      { id: 'et-06', front: 'passport', back: { en: 'travel document', ko: '여권', ja: 'パスポート' }, pronunciation: 'PAS-port' },
      { id: 'et-07', front: 'luggage', back: { en: 'bags for travel', ko: '짐', ja: '荷物' }, pronunciation: 'LUG-ij' },
      { id: 'et-08', front: 'currency', back: { en: 'money system', ko: '통화', ja: '通貨' }, pronunciation: 'KUR-uhn-see' },
      { id: 'et-09', front: 'customs', back: { en: 'border inspection', ko: '세관', ja: '税関' }, pronunciation: 'KUS-tuhmz' },
      { id: 'et-10', front: 'souvenir', back: { en: 'a memento', ko: '기념품', ja: 'お土産' }, pronunciation: 'soo-vuh-NEER' },
      { id: 'et-11', front: 'navigate', back: { en: 'to find the way', ko: '길을 찾다', ja: '道を探す' }, pronunciation: 'NAV-ih-gayt' },
      { id: 'et-12', front: 'layover', back: { en: 'a stop between flights', ko: '경유', ja: '乗り継ぎ' }, pronunciation: 'LAY-oh-ver' },
      { id: 'et-13', front: 'excursion', back: { en: 'a short trip', ko: '소풍', ja: '遠足' }, pronunciation: 'ik-SKUR-zhuhn' },
      { id: 'et-14', front: 'embassy', back: { en: 'diplomatic office', ko: '대사관', ja: '大使館' }, pronunciation: 'EM-buh-see' },
      { id: 'et-15', front: 'boarding', back: { en: 'getting on a vehicle', ko: '탑승', ja: '搭乗' }, pronunciation: 'BOR-ding' },
      // Cloze cards
      { id: 'et-c01', noteType: 'Cloze', front: 'I have a _____ at the hotel.', back: { en: 'reservation', ko: '예약', ja: '予約' }, pronunciation: 'rez-er-VAY-shuhn', extra: 'I have a reservation at the hotel.' },
      { id: 'et-c02', noteType: 'Cloze', front: 'Our _____ time is 3 PM.', back: { en: 'departure', ko: '출발', ja: '出発' }, pronunciation: 'dih-PAR-chur', extra: 'Our departure time is 3 PM.' },
      { id: 'et-c03', noteType: 'Cloze', front: 'What is the final _____?', back: { en: 'destination', ko: '목적지', ja: '目的地' }, pronunciation: 'des-tuh-NAY-shuhn', extra: 'What is the final destination?' },
      { id: 'et-c04', noteType: 'Cloze', front: "Don't forget your _____.", back: { en: 'passport', ko: '여권', ja: 'パスポート' }, pronunciation: 'PAS-port', extra: "Don't forget your passport." },
      { id: 'et-c05', noteType: 'Cloze', front: 'I bought a _____ for my friend.', back: { en: 'souvenir', ko: '기념품', ja: 'お土産' }, pronunciation: 'soo-vuh-NEER', extra: 'I bought a souvenir for my friend.' },
    ],
  },
  {
    id: 'business-english',
    lang: 'en',
    name: 'Business English',
    nameLocal: 'Business English',
    description: 'Professional vocabulary for the workplace and meetings.',
    emoji: '💼',
    accentColor: '#d97706',
    cards: [
      { id: 'bu-01', front: 'negotiate', back: { en: 'to discuss terms', ko: '협상하다', ja: '交渉する' }, pronunciation: 'nih-GOH-shee-ayt' },
      { id: 'bu-02', front: 'deadline', back: { en: 'a time limit', ko: '마감', ja: '締め切り' }, pronunciation: 'DED-line' },
      { id: 'bu-03', front: 'strategy', back: { en: 'a plan of action', ko: '전략', ja: '戦略' }, pronunciation: 'STRAT-uh-jee' },
      { id: 'bu-04', front: 'collaborate', back: { en: 'to work together', ko: '협력하다', ja: '協力する' }, pronunciation: 'kuh-LAB-uh-rayt' },
      { id: 'bu-05', front: 'proposal', back: { en: 'a suggested plan', ko: '제안', ja: '提案' }, pronunciation: 'pruh-POH-zuhl' },
      { id: 'bu-06', front: 'revenue', back: { en: 'income earned', ko: '수익', ja: '収益' }, pronunciation: 'REV-uh-noo' },
      { id: 'bu-07', front: 'investment', back: { en: 'putting money to use', ko: '투자', ja: '投資' }, pronunciation: 'in-VEST-muhnt' },
      { id: 'bu-08', front: 'productivity', back: { en: 'work efficiency', ko: '생산성', ja: '生産性' }, pronunciation: 'proh-duk-TIV-uh-tee' },
      { id: 'bu-09', front: 'stakeholder', back: { en: 'an interested party', ko: '이해관계자', ja: '利害関係者' }, pronunciation: 'STAYK-hohl-der' },
      { id: 'bu-10', front: 'implement', back: { en: 'to put into action', ko: '실행하다', ja: '実行する' }, pronunciation: 'IM-pluh-ment' },
      { id: 'bu-11', front: 'analyze', back: { en: 'to examine in detail', ko: '분석하다', ja: '分析する' }, pronunciation: 'AN-uh-lyze' },
      { id: 'bu-12', front: 'feedback', back: { en: 'response or comments', ko: '피드백', ja: 'フィードバック' }, pronunciation: 'FEED-bak' },
      { id: 'bu-13', front: 'milestone', back: { en: 'an important stage', ko: '이정표', ja: 'マイルストーン' }, pronunciation: 'MILE-stohn' },
      { id: 'bu-14', front: 'delegate', back: { en: 'to assign tasks', ko: '위임하다', ja: '委任する' }, pronunciation: 'DEL-uh-gayt' },
      { id: 'bu-15', front: 'innovative', back: { en: 'introducing new ideas', ko: '혁신적인', ja: '革新的な' }, pronunciation: 'IN-uh-vay-tiv' },
      // Cloze cards
      { id: 'bu-c01', noteType: 'Cloze', front: 'We need to _____ the contract terms.', back: { en: 'negotiate', ko: '협상하다', ja: '交渉する' }, pronunciation: 'nih-GOH-shee-ayt', extra: 'We need to negotiate the contract terms.' },
      { id: 'bu-c02', noteType: 'Cloze', front: 'The _____ is next Friday.', back: { en: 'deadline', ko: '마감', ja: '締め切り' }, pronunciation: 'DED-line', extra: 'The deadline is next Friday.' },
      { id: 'bu-c03', noteType: 'Cloze', front: "Let's _____ on this project.", back: { en: 'collaborate', ko: '협력하다', ja: '協力する' }, pronunciation: 'kuh-LAB-uh-rayt', extra: "Let's collaborate on this project." },
      { id: 'bu-c04', noteType: 'Cloze', front: 'We should _____ the data first.', back: { en: 'analyze', ko: '분석하다', ja: '分析する' }, pronunciation: 'AN-uh-lyze', extra: 'We should analyze the data first.' },
      { id: 'bu-c05', noteType: 'Cloze', front: 'This is an _____ approach.', back: { en: 'innovative', ko: '혁신적인', ja: '革新的な' }, pronunciation: 'IN-uh-vay-tiv', extra: 'This is an innovative approach.' },
    ],
  },
];
